### ISSUE TITLE
Add $file_path wildcard

### ISSUE THREAD

**Issue by pservit** [niosus/EasyClangComplete#176] opened 2016-12-12 20:57 UTC
Please, add support of $file_path wildcard to use it in relative paths (ex. "-I$file_path/../../include")

[settings_storage.py-patch.txt](https://github.com/niosus/EasyClangComplete/files/647189/settings_storage.py-patch.txt)

**Comment by niosus** [comment] 2016-12-12 21:08
I don't think this scales well. The settings are either project specific or folder specific, i.e. there are no settings for a specific view. So you will most likely have wrong includes in most of the cases. What is the situation where you cannot use the path to a project or `.clang_complete` file with relative paths?

**Comment by pservit** [comment] 2016-12-27 17:15
I have project folder with subfolders:


subfolder1
\. includes
\. src

subfolder2
\. includes
\. src

and I need to use includes from current subfolder at first

**Comment by niosus** [comment] 2016-12-28 09:57
In your case, it's easy to add both into either the `common_flags` or `.clang_complete` file with `-Isubfolder1/includes` and `-Isubfolder2/includes`. Or if you want them not to be mixed, you have three options:
1. Use compilation database with proper includes
2. Use CMake and the problem is solved by itself
3. Create 2 `.clang_complete` files in `subfolder1` and `subfolder2` with single line each: `-Iincludes`.

I will close this issue as I don't think adding this functionality will benefit the plugin. I guess it is easier to be confused about it than to actually use it. I think the options I have provided offer exactly what you need. Feel free to continue discussion here should something not be clear for now.

**Closed by niosus** 2016-12-28 09:57 UTC
Labels: discussion, idle
