### ISSUE TITLE
CMake cannot read environment variables

### ISSUE THREAD

**Issue by PatWie** [niosus/EasyClangComplete#294] opened 2017-07-28 18:52 UTC
# Please do this before submitting: #
- [x] check for already solved issues
- [x] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `3126`
- which system are you on: `Ubuntu 16.04`

Do the following:
- add a CMakeLists.txt
with the content
```
if (DEFINED ENV{DUMMY})  
# pass
else()
    message(FATAL_ERROR "DUMMY is not defined. \n  ")
endif()
```

- add `export DUMMY=/tmp` to `.bashrc`.
- restart SublimeText

The console view of sublime gives me
```
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: cmake process finished with code: 1
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: cmake produced output: 
CMake Error at CMakeLists.txt:38 (message):
  DUMMY is not defined.

-- Configuring incomplete, errors occurred!
```

All errors arise, when the include path depends on `DUMMY`.

- open a terminal in Ubuntu and type `printenv DUMMY`, you will see the `/tmp`.

**edit** [this question](https://stackoverflow.com/a/25996724/7443104) might be related but is without any solution. CMake usually relies on several environment variables.

**Comment by rwols** [comment] 2017-07-28 19:12
To access environment variables in cmake, use `$ENV{DUMMY}`. I believe `ENV{DUMMY}` is regarded as an unquoted string. In the context of the `if()` command, you're asking wether the variable denoted by `ENV{DUMMY}` is defined. I don't think that's what you meant to do based on the error message that you're outputting.

**Comment by rwols** [comment] 2017-07-28 21:57
Are you using the CMake package from package control? It should have given you hints:

![schermafbeelding 2017-07-28 om 23 49 27](https://user-images.githubusercontent.com/2431823/28737592-843b7e3e-73ef-11e7-8267-8eb41230fad7.png)
![schermafbeelding 2017-07-28 om 23 49 37](https://user-images.githubusercontent.com/2431823/28737593-846b78a0-73ef-11e7-941e-2bea8ce2cbf9.png)

It seems I forgot to highlight `DEFINED`, should fix that.

**Comment by PatWie** [comment] 2017-07-29 11:29
My cmake is correct! It is about the missing environment variables in a sublime plugin.

I can compile the project from the terminal. Try to type `import os; print os.environ` and you will see the missing paths.

**Comment by rwols** [comment] 2017-07-29 11:40
[You are correct](http://public.kitware.com/pipermail/cmake/2011-October/046706.html), forget what I said about a missing `$`.

**Comment by niosus** [comment] 2017-07-29 21:13
Hey @PatWie thanks for reporting. I am sorry for the inconvenience. Currently, I don't really care in which environment does the sublime text and its subprocesses run. I guess what I would need is smth along the lines of: 
```
import subprocess, os
my_env = os.environ.copy()
my_env["PATH"] = "/usr/sbin:/sbin:" + my_env["PATH"]
subprocess.Popen(my_command, env=my_env)
```
I will keep this issue open and will try to fix the behavior today/tomorrow.

**Comment by niosus** [comment] 2017-07-30 06:34
Ok, @PatWie I have looked a bit deeper and things look bad. The environment is already loaded by default. The issue that you experience is caused by the fact, that sublime text loads a wrong environment. If you run sublime text from the desktop file then your `.bashrc` is never sourced, so you can't get the variables from there. The following example will work:
```bash
export DUMMY=/tmp
subl
```

You will see, that cmake sees the variable. 

The problem is that it is not trivial to start sublime text in a correct environment if you are not willing to start sublime text from terminal every time. I will close this issue here as it is really not the issue of this plugin, but I will try to find a nice way to modify a desktop file for example to pre-load the environment.

**Closed by niosus** 2017-07-30 06:34 UTC
Labels: bug

**Comment by niosus** [comment] 2017-07-30 06:43
I have played with desktop files a bit and have modified the default desktop file of sublime text to run in an interactive bash shell. This ensures, that `.bashrc` is sourced. You can save this file as `~/.local/share/applications/sublime_text.desktop` and it should work for you :
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Sublime Text
GenericName=Text Editor
Comment=Sophisticated text editor for code, markup and prose
Exec=bash -ic "/opt/sublime_text/sublime_text %F"
Terminal=false
MimeType=text/plain;
Icon=sublime-text
Categories=TextEditor;Development;
StartupNotify=true
Actions=Window;Document;
```

**Comment by PatWie** [comment] 2017-08-02 13:20
Thank you for your response. I will look into your solution and try to use it into zsh.
