### ISSUE TITLE
Colored gutter error icon rendered black

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#363] opened 2017-12-11 15:47 UTC
- Sublime Text version: `Version 3.0, Build 3143`
- Which system are you on: `Archlinux`

After a recent update of this plugin, error icons in the gutter started to render as completely black:
![2017-12-11-103134_1200x1883_scrot](https://user-images.githubusercontent.com/578702/33839387-1542883e-de60-11e7-81a4-4737edb246cf.png)

If I switch to `"mono"` however, I think it looks as intended:
![2017-12-11-103257_1200x1883_scrot](https://user-images.githubusercontent.com/578702/33839398-21f17ef0-de60-11e7-9f76-a41df5b44e7e.png)

If I look at the full output log I see nothing suspicious:
[log.txt](https://github.com/niosus/EasyClangComplete/files/1548370/log.txt)

Do you have any idea what might might be causing this? This may be a bug on Sublime's side.

**Comment by niosus** [comment] 2017-12-11 16:03
There is an issue with the tinting in sublime text. I have to admit that I also have not tested this with a light color scheme :) I will look into it. Thanks!

**Comment by niosus** [comment] 2017-12-12 11:36
Unfortunately I cannot reproduce this on my Ubuntu machine. Which theme are you using? Could you try a different one?

**Comment by jdumas** [comment] 2017-12-12 13:01
I am on archlinux. But it behaves consistently on my laptop and my desktop machines. I have quite a few packages installed so it may be that another one is creating some conflict idk. Here is the list of packages that I have installed:

```json
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Anaconda",
		"ANSIescape",
		"ApplySyntax",
		"AutoDocstring",
		"BeautifyLatex",
		"Clang Format",
		"CMakeEditor",
		"Dictionaries",
		"DoxyDoxygen",
		"EasyClangComplete",
		"FileHeader",
		"Hugofy",
		"IntelliDocs",
		"LanguageTool",
		"LaTeX Snippets",
		"LaTeX-cwl",
		"LaTeXTools",
		"MagicPython",
		"Markdown Extended",
		"Markdown Preview",
		"Markdown Table Formatter",
		"MarkdownEditing",
		"MarkdownTOC",
		"Monokai Extended",
		"Non Text Files",
		"OpenCL",
		"OpenGL Shading Language (GLSL)",
		"Package Control",
		"PackageResourceViewer",
		"PlainTasks",
		"Preset Command",
		"Pylinter",
		"SublimeLinter",
		"SublimeLinter-contrib-clang",
		"SublimeLinter-contrib-cmakelint",
		"SublimeLinter-lua",
		"Terminal",
		"Text Pastry",
		"Theme - Alpenglow",
		"Theme - Cyanide",
		"Theme - Piatto",
		"TOML",
		"View In Browser",
		"YcmdCompletion"
	],
	"repositories":
	[
		"https://github.com/titoBouzout/Dictionaries"
	]
}
```

And my config looks like this:
```json
{
	"auto_complete_delay": 200,
	"auto_complete_triggers":
	[
		{
			"characters": ".:>",
			"selector": "source.c++ - string - comment - constant.numeric"
		},
		{
			"characters": "\\",
			"selector": "text.tex.latex"
		}
	],
	"centurion_folder_icons": true,
	"color_scheme": "Packages/User/SublimeLinter/Visual Studio (SL).tmTheme",
	"contrasted_light_quick_panel": true,
	"contrasted_light_sidebar": true,
	"contrasted_light_tabs": true,
	"detect_indentation": true,
	"dictionary": "Packages/Language - English/en_US.dic",
	"ensure_newline_at_eof_on_save": true,
	"external_file_patterns":
	[
		"*.pdf"
	],
	"font_face": "Deja Vu Sans Mono",
	"font_options":
	[
		"subpixel_antialias",
		"gray_antialias"
	],
	"font_size": 8.5,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"icon_file_type_enable": true,
	"ignored_packages":
	[
		"BeautifyLatex",
		"Dictionaries",
		"Markdown",
		"Python",
		"Vintage",
		"YcmdCompletion"
	],
	"index_workers": 4,
	"open_externally_patterns":
	[
		"*.jpg",
		"*.jpeg",
		"*.png",
		"*.gif",
		"*.zip",
		"*.pdf"
	],
	"overlay_scroll_bars": "enabled",
	"prevent_bin_preview": true,
	"rulers":
	[
		80,
		100,
		120
	],
	"scroll_past_end": false,
	"scroll_speed": 0.0,
	"spell_check": true,
	"status_bar_brighter": true,
	"tabs_padding_small": true,
	"tabs_small": true,
	"theme": "Piatto Light.sublime-theme",
	"trim_trailing_white_space_on_save": true,
	"word_wrap": true,
	"wrap_width": 0
}
```

Again, this may very well be a pb on my side, but I am having trouble identifying where it comes from...

**Comment by niosus** [comment] 2017-12-12 14:07
I feel Like this line causes it:
```
"color_scheme": "Packages/User/SublimeLinter/Visual Studio (SL).tmTheme",
```
But i'm not entirely sure. It looks a bit funny that the scheme is in the `SublimeLinter` folder.

**Comment by jdumas** [comment] 2017-12-12 14:24
Yeah probably. What's happening is that SublimeLinter is customizing themes to be able to add its own [gutter marks](http://www.sublimelinter.com/en/latest/gutter_themes.html) or something. I don't remember where it is explained in the doc, but whenever I select my own theme in Sublime, SublimeLinter will create its own (modified) version and place it in the `SublimeLinter/` folder. I'll try to see if I can get around this.

**Comment by niosus** [comment] 2017-12-12 15:27
Hmmm. I am also using SublimeLinter, but I don't have this behavior. It must be related to their note: 
> Colorized icons are in fact mostly white; they are displayed here as they appear when drawn by SublimeLinter, tinted with the error or warning color. Creating the icons white allows the tint color to come through unchanged.

The color icon I provide is red and maybe it interferes with the linter themes. I guess this is why I included the `mono` one :) I knew smth like this is coming :)

**Comment by niosus** [comment] 2018-09-17 12:00
I think I will close this issue for now as I don't see what I can do about it now.

**Closed by niosus** 2018-09-17 12:00 UTC
Labels: bug, cannot-reproduce
