### ISSUE TITLE
ECC doesn't find symbols, but Sublime does

### ISSUE THREAD

**Issue by spencer-evans-pnt** [niosus/EasyClangComplete#210] opened 2017-02-13 20:05 UTC
Maybe I'm not understanding exactly how EEC works, but I think I found a bug:

Sublime's built in symbol definition finder seems to work, but EEC cannot see the same symbol.

On hover over:
![1](https://cloud.githubusercontent.com/assets/15803549/22900737/046630b8-f1f5-11e6-90e4-05914cfec708.png)

On click:
![2](https://cloud.githubusercontent.com/assets/15803549/22900745/08e2eb7c-f1f5-11e6-91c6-fee4bcee4c75.png)

And my sublime-project file:
![3](https://cloud.githubusercontent.com/assets/15803549/22900758/17c6c7f8-f1f5-11e6-8bb3-9b15d1cfdd8a.png)

Thank you ahead of time, and for all the awesome work you've done to build this.

Spencer

**Comment by simia** [comment] 2017-02-13 21:36
Hi,
This is probably configuration issue. ECC can't find header with VRMenuObject declaration (this can be caused by missing -I in include file or mising #include directive in C++ file). 
Could you set ECC to print debug information and copy paste any errors from Sublime console?
Also maybe try using absolute path in ecc_common_flags?

**Comment by niosus** [comment] 2017-02-14 15:14
I will close this issue as it is a configuration issue. I understand it is not that easy to configure the include paths correctly. I hope that when I will have the time to write proper documentation for the project it will be easier. In any case, I would suggest you to use a build system like CMake if you can. This way it is guaranteed that if you can build it anywhere, the plugin will be able to do it too.

Please make sure as already stated by @simia that you have the correct include paths. This issue is definitely caused by this. Make sure that paths are relative to the root of the project or, as suggested, try to use absolute paths.

**Closed by niosus** 2017-02-14 15:14 UTC
Labels: invalid, question

**Comment by spencer-evans-pnt** [comment] 2017-02-14 15:28
Thanks for your help and recommendations. Things came up, and I haven't had time to try the recommended solutions, but I'll report back here if I find it isn't a configuration issue.

Cheers
