### ISSUE TITLE
Crash after upgrade to 3.4.1

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#220] opened 2017-03-10 00:49 UTC
As the title.

**Comment by niosus** [comment] 2017-03-10 15:08
Please set `verbose` to `true` restart sublime text make it crash and copy the full log here. I cannot help you with no information.

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:13
I don't know how to get the full log when sublime is crash.

**Comment by niosus** [comment] 2017-03-10 15:15
What do you mean by Sublime Text crashing? You mean the plugin host? If this is the case, then you need to press <kbd>Ctrl</kbd> + <kbd>`</kbd> and copy everything from the console here.

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:17
I mean system is not responding.

**Comment by niosus** [comment] 2017-03-10 15:18
This is really strange. Which system are you on?

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:18
macOS.

**Comment by niosus** [comment] 2017-03-10 15:21
Unfortunately I cannot reproduce this on my Linux system and I don't have a mac. Unfortunately, for now I can only suggest you not to use the `autocomplete_all`.

Did it start happening only after a recent update?

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:28
I think the problem is status indicator, because after I've comment out this code block from `plugin/tools.py`:
``` python
    @staticmethod
    def set_status(message):
        """Set status message for the current view."""
        view = sublime.active_window().active_view()
        view.set_status("000_ECC", message)

    @staticmethod
    def erase_status():
        """Erase status message for the current view."""
        view = sublime.active_window().active_view()
        view.erase_status("000_ECC")
```
EasyClangComplete work very well for me again(sorry my english is terrible).

**Comment by niosus** [comment] 2017-03-10 15:37
Don't worry about your english :) It's good enough to explain the issue.

Ok, so it is definitely something with the status. I will think about it and will come back to you once I have an idea of what can cause this.

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:38
Thanks!! :smile:

**Comment by ooJerryLeeoo** [comment] 2017-03-10 15:43
I think create a new option to disable status indicator is a good idea, example: 
``` json
 status_indicator: false // or true
```

**Comment by niosus** [comment] 2017-03-10 15:45
Yeah, I was thinking about this as a fast fallback. But there is still a real issue behind this. It should just work on all systems. However, I might add this on the weekend.

**Comment by ooJerryLeeoo** [comment] 2017-03-10 16:09
I think this issue is not only happened on macOS, I've found this issue by set  `autocomplete_all` to `true`, and type `#include <string>` into a C/C++ file and try type fast.

**Comment by niosus** [comment] 2017-03-10 16:18
Ok, reproduced. You're right. I will definitely have a look at it on the weekend. Thanks for reporting.

**Comment by parnham** [comment] 2017-03-10 21:33
This is affecting me too, but with `autocomplete_all` set to false.
(ubuntu x64)

**Comment by ooJerryLeeoo** [comment] 2017-03-11 00:20
You're right.

**Comment by niosus** [comment] 2017-03-11 00:24
Damn. :( will either fix or roll back over the weekend. Sorry for that.

**Comment by ooJerryLeeoo** [comment] 2017-03-11 11:28
I have a feeling that the problem is ECC changing status indicator too frequently.

**Comment by niosus** [comment] 2017-03-11 13:11
I guess this is some mistake of mine with progress indicator thread. Maybe I spawn a new thread even though the old one is alive. This can lead to status being updated really frequently.

**Comment by silva6** [comment] 2017-03-11 14:28
I also have problem at the version of  3.4.0/1. The plugin will cause sublime dead and cannot do anything, even if close the app.

**Comment by niosus** [comment] 2017-03-11 14:33
Ok, this seems to be much more prevalent on OSX. I will try to fix this today.

**Comment by niosus** [comment] 2017-03-11 15:55
Hey guys, I have changed the way I address the animation thread. It now creates a single thread an just updates animation when needed. This should avoid issues with generating new threads. Please check if this solves it for you. I was unable to crash sublime text on my system with this fix.

**Comment by ooJerryLeeoo** [comment] 2017-03-11 22:34
It's now work well for me.

**Comment by niosus** [comment] 2017-03-11 23:17
I have pushed a new release with the changes (will be live in half an hour or so). I will close this issue for now, but please reopen if something still does not work.

**Closed by niosus** 2017-03-11 23:17 UTC
Labels: bug
