### ISSUE TITLE
Support cmake CMAKE_EXPORT_COMPILE_COMMANDS and compile_commands.json

### ISSUE THREAD

**Issue by milot-mirdita** [niosus/EasyClangComplete#19] opened 2016-05-28 14:38 UTC
Thanks for the plugin! It would be cool, if ECC could read the compile_commands.json file that cmake generates if you pass -DCMAKE_EXPORT_COMPILE_COMMANDS=ON.
In this file it lists all flags that where used for every file.

The compile_commands.json output looks like this:

```
[
{
  "directory": "/Users/me/mytool",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DAVX2 -I/Users/me/repositories/mytool/src/commons -I/Users/me/repositories/mytool/src/util -I/Users/me/repositories/mytool/lib/getoptpp    -march=native -mavx2 -mfpmath=sse -std=c++0x -m64 -pedantic -Wall -Wextra -Winline -Wdisabled-optimization -Wno-unused-parameter -stdlib=libc++ -O3 -DNDEBUG  -march=native -mavx2 -mfpmath=sse -O3 -DNDEBUG -ffast-math -fno-exceptions -ftree-vectorize -fno-strict-aliasing   -o src/CMakeFiles/mytool.dir/mytool.cpp.o -c /Users/me/repositories/mytool/src/mytool.cpp",
  "file": "/Users/me/repositories/mytool/src/mytool.cpp"
}
...
]
````

**Comment by niosus** [comment] 2016-05-28 14:56
Yes, I was already thinking about this for some time. It should be trivial to implement, but I don't know if clang will be ok with all the flags. They are usually for gcc (at least in my case most projects are compiled with gcc). But let's see. I will implement it and will test on some of the project of mine.

I know that YouCompleteMe discourages to use the `compile_commands.json` and the guy who implemented it has a lot more experience in it than I do and probably has his reasons. But let's see.

**Comment by niosus** [comment] 2016-05-29 09:57
It might be harder to do in a right way than I tought. One has to provide a path to the generated database. It depends on how the build was carried out. Also, it will not work should people not use CMake. I don't say I won't do this, but I need to think how to do it in a non-confusing and non-breaking way. So it'll take more time, I guess.

**Comment by jdumas** [comment] 2016-06-08 11:09
How about having the plugin generate a `.clang_complete` by calling clang when it detects the presence of a `CMakeLists.txt`? Using something like this:
https://www.guyrutenberg.com/2013/01/29/vim-creating-clang_complete-using-cmake/

**Comment by niosus** [comment] 2016-07-02 11:48
Ok, I've finally found some time to work on this, sorry for the delay, a busy summer in the full-time-job world. My current idea would be:
- [ ] detect if there is a `CMakeLists.txt` file in the root of the project. 
- [ ] If yes, create a build folder in temporary directory and will run `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON <path_to_CMakeLists.txt>` from there.  This will generate the compilation database. 
- [ ] parse created `compile_commands.json` for all `command` entries and save all unique `-I` and `-isystem` entries in some list. 
- [ ] this list will then be saved to memory as part of the completer (or to a `.clang_complete` file). This step is up for discussion and I would be grateful for any input from you.

I will track the progress here.

What do you guys think?

**Comment by niosus** [comment] 2016-07-03 16:43
7545f4534aaea007fed6a56ab020a43c79430198 to the new branch adds this functionality but needs to be tested and heavily cleaned up. But the concept works.

**Comment by niosus** [comment] 2016-07-04 21:43
Ok, now everything is implemented in a separate branch. I need to talk to somebody about what would be the expected behavior. I want to make is as simple and unintrusive as possible, but I don't want to scare the user by doing something behind his back. I will describe what I have now and will point out some questions along the way.

I see it this way:

1.  whenever a new `C/C++` file is opened we search for a `CMakeLists.txt` file in the project folder (**Q1:** should we only do it if a project is open? What to do if the user has no project open?).
2.  if `CMakeLists.txt` is found we generate `.clang_complete` by parsing unique `-I` and `-isystem` entries from `command` keys in `compile_commands.json` which we generate by running `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON <path_to_CMakeLists.txt>` from `/tmp/EasyClangComplete/build`. **Q2:** what do we do if `.clang_complete` file already exists? Do we overwrite it? Do we ask the user?
3. We use `.clang_complete` file for code completion as before.

Discussion is welcome. I want to be sure I didn't miss something important before I push things to `master`

**Comment by assumptionsoup** [comment] 2016-07-04 22:46
You could also take the manual approach by providing a user-executed command?  Something like "Generate clang_complete from cmake"?  The command could:

- Check for CMakeLists.txt.  If not, error and tell the user.
- Check for .clang_complete.  If it finds one, ask if the user wants to overwrite or abort.

As a bonus, the command could save a hash of the CMakeList.txt so the plugin could detect if .clang_complete is invalid and ask the user to reissue the generation command.

Or if you think the process should be completely automated and not use commands - but also not screw anything up - you could have EasyClangComplete search for two .clang_complete files.  The default `.clang_complete` would be used if found, otherwise it could fall back to `.clang_complete_cmake`, which could be the generated file.

That's my two cents.  Though, take my suggestions with a grain of salt, since I can't run your plugin on windows yet :D

**Comment by niosus** [comment] 2016-07-05 07:48
@assumptionsoup this actually sounds nice. I guess having two files is the best I can do. I thought of a user command, but then I would need to educate the users that they actually have to call it before using the plugin. And I would really love to reach out-of-the-box experience if possible. 

Yeah, Windows is a bummer. Annoys me as hell :) 
But you can run it using the clang binary, can you?

**Comment by jdumas** [comment] 2016-07-05 08:08
For Q1, I would search parent folders recursively until I reach a `CMakeLists.txt` with a "project" instruction in it. This does not have to do anything with with being a project in sublime I guess. Where it gets tricky is that we can have nested `CMakeLists.txt`, and I'm not sure it is possible to guess which one will export the right compile commands (Imagine a master `CMakeLists.txt` with nested projects, it is not guaranteed that the root CMake file will work). I guess we can have a default reasonable behavior (find the first `CMakeLists.txt` with a `project` instruction in it), and provide a per-project option for the user to configure the path of the CMakeList.txt to call (if we are in a project it is reasonable to assume we have only 1 root `CMakeLists.txt`).

For Q2 I would provide a plugin option which is a "priority list" of the behavior to adopt. A reasonable default would be `["clang_complete", "cmake"]`, meaning that if a `.clang_complete` is already there, it will be used (if it is manually generated by the user chances are it is correct). Then, if it is not found, it will fallback to the CMake-generated one. And then it is easy to let the user change the default behavior to what they want.


And last point, I don't understand why you want to parse only the `-I` and `-isystem` from the `.json` file? Complex project are full of `-Dwhatever` and other options (`-fopenmp=libomp`, `-std=gnu++11`, etc.). If you call `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON <path_to_CMakeLists.txt>`, you can also set the compiler to be clang with `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ` (eventually replace `/usr/bin/clang` by a user-provided path to the `clang` executable). In which case you can probably reuse the whole set of options directly.

**Comment by assumptionsoup** [comment] 2016-07-05 18:42
@niosus I can run the binary in general, but not for my current project.  I need to send clang more includes than the maximum line length Windows allows for commands (my .clang_complete file is 1400 lines long).  Clang doesn't seem to have any ability to take includes from a file - and why would it, Linux is really good at that sort of thing!  Unfortunately, my project also requires Windows, so I'm stuck with this mess!

**Comment by niosus** [comment] 2016-07-05 20:32
@assumptionsoup ah, yep, now I remember. Hope we will eventually solve this.

@jdumas I strongly believe that "done is better than perfect". I feel that iterative approach would be better, so I would probably start with a single searching a single `CMakeLists.txt` and parsing its output. If the other ones are included with `add_subdirectory(...)` then all the commands should be in the compilation database. The problem with searching the ones that contain `project` line is that if they are part of a chain of `CMakeLists.txt` which are included into one another, then it may be that they don't actually compile on their own (correct me if I'm wrong). So I would start with searching top-most `CMakeLists.txt` and getting all the `-D`, `-I` and `-isystem` flags from it. That will be a start. After this is done I would start to iteratively improve the thing upon need. It never works for me when I try to do everything perfect from the start. Especially considering that I can now only work on it nights :)

The reason I don't want to take all flags is that under current system design of the plugin I will need to do many changes to account for flags like `-std=gnu11`. But let's see how it evolves.

As for your last question: I believe that what you ask is possible. Currently the plugin searches the first `.clang_complete` starting from the current file up until the project directory or root if no project available. Only this file will be used for completion. So theoretically I could create a `.clang_complete` file near a parsed `CMakeLists.txt`.

**Comment by jdumas** [comment] 2016-07-06 05:52
Sure, I understand. I'm just offering offering some suggestions, you take what you want from there. To be honest I think parsing for a `project()` command would be quite fragile. Looking for the top-most `CMakeList.txt`, and offering a per-project option to let the user give the `CMakeList.txt` would be enough for most case (let the user decide instead of trying to be too smart).

As for the flags like `-fopenmp=libomp` of `-std=gnu++11`, I haven't looked at the current architecture of your plugin, so I don't know how hard it will be to make them work. But this can be another “enhancement” ticket =).

**Comment by niosus** [comment] 2016-07-06 08:09
@jdumas yep, totally agree that it's another "enchancement" ticket :) I will start with a simple approach and will try to do everything modular. Then it will be easy to extend it. I will probably encapsulate all flags management into a single class that will have a method `get_flags(view)`. It will know by itself if it should search for `CMakeLists.txt`, `.clang_complete` and which of them it should generate. I feel like it's a good decision.

**Comment by niosus** [comment] 2016-07-06 11:44
I guess for a start I will implement something along this sketch:
![screenshot from 2016-07-06 13 42 44](https://cloud.githubusercontent.com/assets/1893598/16616758/a03f882e-437f-11e6-8190-0f7e16768fbe.png)

**Comment by jdumas** [comment] 2016-07-07 07:41
“Cmake Change -> Yep” should point to “.clang_complete exists?”. Otherwise looks good.

**Comment by niosus** [comment] 2016-07-07 07:54
Yep, you're right. Changed the picture. Although, I guess at some point the user may make it persistent. 
I will try to finish this on the weekend.

**Comment by jdumas** [comment] 2016-07-07 08:27
What do you mean by "make it persistent"? If this is a plugin setting, there would be no need to as every time the cmake is updated. The setting could be {"keep", "overwrite", "ask"}.

**Comment by niosus** [comment] 2016-07-07 08:29
Yep, a plugin setting is what I am thinking. It can be updated automatically if the user chooses smth like "yes, and don't ask again".

**Comment by niosus** [comment] 2016-07-10 00:18
Ok, so it seems to be all working. I will be adding more tests tomorrow probably to be sure it can roll out smoothly. Also some tweaking of settings names and messages is needed. As well as some code cleanups. But overall:

- there is a setting to use cmake to generate flags
- there is a setting to pick a strategy of how to deal with conflicts, e.g. `.clang_complete` already exists. It can be one of:
    + `ask` [default]: ask the user what to do. The user has three options: `overwrite`, `merge` and `Cancel`.
    + `merge`: merge all existing flags with new ones. Exact dublicates will be avoided.
    + `overwrite`: ignore current content of `.clang_complete` file and write new flags instead
    + `keep_old`: ignore the generated flags, keep old ones.
- the flow is as described on the image above in this thread and seems to function (again, more testing is needed).

It would be cool if anyone could test this out while it's still in the separate branch. I don't want to roll out this too fast because it may potentially break someone's workflow. So I want to be sure everything works.

**Comment by niosus** [comment] 2016-07-11 14:38
Bumped into an issue that some more or less esoteric build systems require specific cmake_config_path that is set when initializing terminal. These variables will not be initialized by python subprocess, so the user will need to take care of that himself.

**Comment by niosus** [comment] 2016-07-13 14:51
Oh, while everything seems to work in the branch, I have stumbled upon this thread on StackOverflow and they suggest, that libcland python bindings can read compilation database on its own: http://stackoverflow.com/a/38353410/1763680

**Comment by jdumas** [comment] 2016-07-13 16:35
If you can load the CMake generated `compile_commands.json` directly from the clang python binding, that sounds even better =)

**Comment by niosus** [comment] 2016-07-13 16:40
@jdumas yep, I was also pleasantly surprised. Now I will need to test this.

**Comment by niosus** [comment] 2016-07-28 14:15
Ok, everything is in master now and works on Linux and osx. The problem is again with Windows. As there seems to be no way to generate `compile_commands.json` on windows. Does anyone use cmake on windows? Can you generate the compilation database?

**Comment by niosus** [comment] 2016-07-29 14:19
Ugh... CMake doesn't generate `compile_commands.json` on Windows when the compiler is from VS... Which means that I will need to to also account for the fact that sometimes there is going to be a file `ALL_BUILD.vcxproj` (which is just an xml) and I will probably need to parse this one...

It turned out to be much uglier than I anticipated. Does anyone have better ideas?

**Comment by merlinthered** [comment] 2016-08-01 08:52
I just wanted to point out that just running the cmake command without any command line arguments might not be enough. Sometimes it is necessary to specify additional options when running cmake, and these can not always be reasonably set as a system-wide default. You should at least add a way of specifying additional cmake parameters on a per-project basis.

As a general approach, why don't you let the user set the cmake build directory for the project, so you can just use the one the user is using anyway. That way there's no need to run cmake from your plugin (which can be very slow anyway), and you are sure to use the exact same configuration the user is using.

**Comment by niosus** [comment] 2016-08-01 12:30
@merlinthered this makes everything even harder than it is. What command line arguments are you talking about?

I see here two different things I may need to target:
- out of the box experience. To ensure that relatively simple projects can be built using cmake without the user even knowing.
- custom configurations for a user that needs to run a complex project that takes quite a while to run cmake.

I see these like this. First is much more important for me as the philosophy of this plugin, so I would target out-of-the-box experience first and then find ways to specify arguments and, potentially the folder of cmake build artifacts for the second case. Otherwise, there is the danger that this simply will never be perfect enough to be shipped.

**Comment by merlinthered** [comment] 2016-08-01 14:07
I am mainly talking about custom options cmake projects define, e.g. to enable or disable different features. If you look at VTK, which CMake was made for, it has a huge number of custom-defined keys for this purpose. You can run cmake without any options, and it will set defaults for these keys, but you have no way of knowing if these are the ones the user is using or not.

Imagine a developer working on their own project that they want to ship with a CMake build system. The project might have some testing routines that an end user would likely never enable, and that are therefore disabled by default. The developer will have them enabled most of the time though.

This is why I suggested just using the info that is available in the CMake build directory the user is using. That way you don't have to guess anything. This would require the user to have run cmake at least once, but I don't think this is an unreasonable requirement. I think looking for a build/ directory under the project root as the default guess for this build directory's location would be reasonable.

**Comment by rchl** [comment] 2016-08-26 19:53
Do you really think the plugin itself should handle all the logic related to different build systems? Typically (at least with SublimeClang and Vim's YouCompleteMe) this is solved by just specifying external script whose job is to provide all the compile flags for given input path.
I work with Chromium and ninja build system and there exist scripts already that do all the needed work for this setup.
I'm not agree with the philosophy itself, but I don't think plugin like that should even attempt at compiling. I just don't expect my editor to produce side effects behind my back.

**Comment by merlinthered** [comment] 2016-08-26 19:59
That was also my concern. We need an elegant solution for automatically finding the correct include paths. Letting the user specify a script that does this might be the most universal solution. Then, some predefined solutions for common build systems might be shipped with the plugin.

**Comment by niosus** [comment] 2016-08-29 08:16
Guys, I totally agree with you. I would love to avoid doing anything from within the plugin. However, the plugin has to guess some things. The original idea behind this plugin was to make things simple. Usually it means giving up on some functionality. I wanted to enable most people with relatively simple projects to use sublime text as their IDE. From my point of view there is always a tradeoff between simplicity and verboseness. The more internals I show to the user the more confused will the non-experts be.

I believe that for an expert users the tools are good enough already. We already have ycmd and its spinnoffs and rtags. These are great plugins. More powerfull than this one by far.

In this project I decided to take the courage to make some decisions for the users. Like guessing which build system they are using and getting build flags from it. There is a lot of hidden difficulties here. I guess running a cmake command is not too demanding in general. 

And another important point - this is my hobby project. I only have this much time after work to do it and sometimes it is harder than in other times. So the only way I can do this is to do things iteratively. Meaning that I explicitly will not aim to perfect the functionality on the first iteration. This is the way I will burn out and drop the project entirely. Iteratively approaching something usable is the only way for me, sorry.

As for other build systems - if you can point me to scripts you were talking about I will gladly check them out. I am happy to incorporate these into the plugin if the general script run time is not too long.

Mind that there is always a way to just define a `.clang_complete` file with all the flags in the project.

**Comment by rchl** [comment] 2016-08-29 10:00
> I believe that for an expert users the tools are good enough already. We already have ycmd and its spinnoffs and rtags.

I haven't tried those, but I was hoping that this plugin will become next SublimeClang for me. :) Not much is really missing, just a way to specify compile flags dynamically.

> Mind that there is always a way to just define a .clang_complete file with all the flags in the project.

That's not really a workable solution with more complicated projects. I work on a project with thousands of files, where there are many targets and each can have different compile flags and include paths. The build system (ninja in that case) needs to be leveraged to provide those. Any static list with arguments will just not work good enough.

I don't think that having an option to provide a string would make the plugin more complicated to use for non-experts. It's just a additional setting in the settings file. Not like it bloats the UI as there is no UI in that case. But of course it makes plugin internals more complicated and might cause bugs. But I understand what you wrote and won't pressure you to do anything against your idea.

**Comment by merlinthered** [comment] 2016-08-29 10:09
> Guys, I totally agree with you. I would love to avoid doing anything from within the plugin. However, the plugin has to guess some things. The original idea behind this plugin was to make things simple. Usually it means giving up on some functionality. I wanted to enable most people with relatively simple projects to use sublime text as their IDE. From my point of view there is always a tradeoff between simplicity and verboseness. The more internals I show to the user the more confused will the non-experts be.

I agree with the sentiment of making things simple for getting started. The name of the plugin already implies this. Choosing sensible defaults is a huge part of this. Still, there can be more advanced options in the background for people who need them.

> And another important point - this is my hobby project. I only have this much time after work to do it and sometimes it is harder than in other times. So the only way I can do this is to do things iteratively. Meaning that I explicitly will not aim to perfect the functionality on the first iteration. This is the way I will burn out and drop the project entirely. Iteratively approaching something usable is the only way for me, sorry.

This is only natural and you should in no way feel pressured to more work than you are willing to put in. This is an open source project, and I think it's important that we discuss things like this, even if you can't implement them yourself. The answer from your side to this should then be: "Why don't you implement it yourself and submit a pull request". In fact, I have been meaning to contribute some code to the plugin, but just like you, I have limited spare time and many things to choose from in how I spend that time. Discussions like this can be good points of reference for other people using the plugin who maybe want to contribute as well.

**Comment by niosus** [comment] 2016-08-29 10:22
@rchl @merlinthered yes, totally! Please do not read my response as "won't fix, forget it" :smile: 

I love that you guys start discussions and this is the only way to get a feeling of what should be done and to have some discussions on the ways it may be carried out, so big thanks for that! Also, I don't have much experience in open source, so this is an awesome experience to actually communicate with the community. I guess I am also a bit scared to lose motivated people that would just think that the project is abandoned or something, just because there is a tough period at work on my side :smile: 

I am really happy about pull requests, so do not hesitate to submit them at your own pace. Please also do not hesitate to change things you think should be done differently (or just start issues with discussions about it) as it is always easier to spot errors in someone else's code than in you own, so critics is also much appreciated.

@rchl I have nothing against complicating the internals and introducing new bugs :) The only thing I would love to avoid is the complicated setup for the end user. So could you please just elaborate more on this:
> It's just a additional setting in the settings file.

I am willing to add this build system too if there is a nice way to generate the flags with this build system.
I have never worked with ninja, so links to educate me on essentials will also be welcome.

**Comment by rchl** [comment] 2016-08-29 11:09
I'm thinking about just exposing a setting that could be set to a script that provides compilation flags (all, including include paths, defines, other flags).

For ninja there is a script [1] that is made to be used with SublimeClang. The meat of the functionality is in another script [2] that it uses. Basically it uses ninja `tools` (see `ninja -t list`) to get compilation commands for given file path. It looks like the script is not really chromium specific so it could indeed be integrated 'natively' into the plugin.

[1] https://cs.chromium.org/chromium/src/tools/sublime/ninja_options_script.py?type=cs&sq=package:chromium
[2] https://cs.chromium.org/chromium/src/tools/vim/chromium.ycm_extra_conf.py?type=cs&sq=package:chromium

**Comment by niosus** [comment] 2016-08-29 11:22
Thanks! Will look into it at some point! Thanks for the references. Looks promising. I just wonder how much does it really play the role that they are doing it for YouCompleteMe plugin.

**Comment by rchl** [comment] 2016-08-29 12:02
The script doesn't have any dependencies on YouCompleteMe plugin. I've used it successfully with SublimeText. Just historical artifact that it's in that directory.

**Comment by niosus** [comment] 2016-08-30 07:51
Ok, thanks for the explanation!

**Comment by niosus** [comment] 2016-08-31 08:52
I will close this issue as what is proposed here is implemented. For ninja build system discussions let's move to #76

**Closed by niosus** 2016-08-31 08:52 UTC
Labels: enhancement
