### ISSUE TITLE
Completions from *.sublime-completions files are hidden when using EasyClangComplete plugin

### ISSUE THREAD

**Issue by dannftk** [niosus/EasyClangComplete#497] opened 2018-09-21 09:59 UTC
I have made a [post](https://forum.sublimetext.com/t/completions-from-sublime-completions-files-are-hidden-when-using-easyclangcomplete-plugin/39070) concerning this issue, please take a look
It seems to be a general issue of parsing completion list upon returning from 'on_query_completions' of each eventListener in SublimeText3
I issue this here in case someone faces this to let them know
 Also marked it in the related [issue](https://github.com/SublimeTextIssues/Core/issues/819)

**Comment by niosus** [comment] 2018-09-24 08:31
As far as I understood from the thread you linked, the issue is related to SublimeTextIssues/Core/issues/819 and so is not really on the side of the plugin.

**Comment by dannftk** [comment] 2018-09-24 12:30
Ok, you definitely can close the issue but I like to let the other users of ECC know the issue may expose when using ECC

**Comment by niosus** [comment] 2018-09-24 12:33
I totally support you in this and thanks for opening it. I will close it once it is resolved, I guess.

**Closed** 2018-12-22 15:36 UTC
Labels: blame-somebody-else, bug, wontfix
