### ISSUE TITLE
No Autocompletion for 3rd Party Library Macros

### ISSUE THREAD

**Issue by SubhamoyS** [niosus/EasyClangComplete#67] opened 2016-08-22 09:21 UTC
With libraries like `gflags` and `glog`, macros used for variable declaration are not shown.

```
#include <gflags/gflags.h>

DEFINE_ 
```

At this point, it should give choices of:

```
DEFINE_bool
DEFINE_int32
DEFINE_int64
DEFINE_uint64
DEFINE_double
DEFINE_string
```

But I get nothing. Could you please verify this?

**Comment by niosus** [comment] 2016-08-29 08:29
Hey, thanks for the issue. I guess the issue here is that there is no trigger when you try to complete it.

The problem is that I use `libclang` and in particular a function `clang_codeCompleteAt`. The [documentation](http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html#ga50fedfa85d8d1517363952f2e10aa3bf) to this function states this:

> This function performs code completion at a particular file, line, and column within source code, providing results that suggest potential code snippets based on the context of the completion. The basic model for code completion is that Clang will parse a complete source file, performing syntax checking up to the location where code-completion has been requested. At that point, a special code-completion token is passed to the parser, which recognizes this token and determines, based on the current location in the C/Objective-C/C++ grammar and the state of semantic analysis, what completions to provide. These completions are returned via a new CXCodeCompleteResults structure.

> Code completion itself is meant to be triggered by the client when the user types punctuation characters or whitespace, at which point the code-completion location will coincide with the cursor. For example, if p is a pointer, code-completion might be triggered after the "-" and then after the ">" in p->. When the code-completion location is afer the ">", the completion results will provide, e.g., the members of the struct that "p" points to. The client is responsible for placing the cursor at the beginning of the token currently being typed, then filtering the results based on the contents of the token. For example, when code-completing for the expression p->get, the client should provide the location just after the ">" (e.g., pointing at the "g") to this code-completion hook. Then, the client can filter the results based on the current token text ("get"), only showing those results that start with "get". The intent of this interface is to separate the relatively high-latency acquisition of code-completion results from the filtering of results on a per-character basis, which must have a lower latency.

Which means that it is intended to autocomplete only on triggers. So for now I am afraid this is too far out of the scope of the work I am physically able to do. So for now it is a `wontfix` for me. I am really sorry for this, but I will close it for now.

If you stumble upon something useful to the topic feel free to write it here or even reopen the issue if it is something implementable through python bindings.

Sorry for inconvenience.

**Closed by niosus** 2016-08-29 08:29 UTC
