### ISSUE TITLE
Oasis theme failing to show popups

### ISSUE THREAD

**Issue by Eman7C7** [niosus/EasyClangComplete#462] opened 2018-04-27 12:49 UTC
# What happens:  #
An issue with Oasis theme failing to show popups because of highlighting error. Version of clang, and subl are irrelevant as discussed privately.

<details>
<summary>Log that illustrates the issue: </summary>
  
```

mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Failed to get Sublime highlighter object!
mdpopups: Traceback (most recent call last):
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 619, in show_popup
    nl2br=nl2br, allow_code_wrap=allow_code_wrap
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 322, in _create_html
    allow_code_wrap=allow_code_wrap
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 435, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"').replace('\n', '')
  File "/home/eman/.config/sublime-text-3/Packages/python-markdown/st3/markdown/__init__.py", line 368, in convert
    self.lines = prep.run(self.lines)
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 564, in run
    lines = self.search_nested(lines)
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 483, in search_nested
    self.eval_fence(ws, content, start, end)
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 331, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 370, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang)
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 530, in highlight
    linespecial=linespecial
  File "/home/eman/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 324, in highlight
    code = self.sublime_hl[1].syntax_highlight(
AttributeError: 'NoneType' object has no attribute 'syntax_highlight'

```

</details>

**Comment by niosus** [comment] 2018-05-01 10:52
This looks like an issue with mdpopups or the theme itself. @facelessuser did you encounter issues like that when using mdpopups?

**Comment by facelessuser** [comment] 2018-05-01 13:12
Sublime version? Version of mdpopups? Link to theme you are using? And lastly, values of any and all mdpopups options in your user Preferences.sublime-settings file?

Please answer all these questions so I can determine if this is a mdpopups issue.

**Comment by niosus** [comment] 2018-05-01 13:51
@Eman7C7 we should not have skipped the info step in the issue submitting :) Could you provide the needed info? I cannot reproduce this issue on my machine, so you're our only hope. It is strange that I cannot reproduce this. What happens if you backup your settings and try on a clean install of sublime text with just this plugin and the Oasis theme enabled?

You can get the version of `mdpopups` by calling these commands in the console of your sublime text:
```
import mdpopups
mdpopups.version()
```

As for the settings we are using for mdpopups @facelessuser, we are not setting anything apart from a custom css. I am using css defined here: 
https://github.com/niosus/EasyClangComplete/blob/cb828483004a2593ed3faeaaa413c6720959913e/plugin/popups/popup.css#L1-L10

The popup creation is just passing a markdown text to it, so I guess nothing interesting going on there, but for completeness, everything happens in this [file](https://github.com/niosus/EasyClangComplete/blob/master/plugin/popups/popups.py) (might be non-trivial to read as it contains some logic specific to this plugin).

**Comment by facelessuser** [comment] 2018-05-01 14:02
Sublime version may be very important as there were a couple of versions that had some override issues with package files. I know you aren't setting any mdpopups options, but I need confirmation from @Eman7C7. It will help me determine code paths that are getting executed.

**Comment by niosus** [comment] 2018-05-01 14:09
Ok, thanks for your time and the info on the versions that might break :) Let's see if @Eman7C7 can still reproduce this and the version of sublime text and mdpopups that he runs.

**Comment by facelessuser** [comment] 2018-05-01 15:12
Looking at this more, most likely it is a color scheme parsing issue, so getting a link to the color scheme is most likely going to be key to figuring out this issue (along with versions).

**Comment by Eman7C7** [comment] 2018-05-02 08:03
Sublime Text Version: 3.0 build 3143.
```
>>> mdpopups.version()
(3, 3, 3)
```
link to color scheme: [Oasis Theme](https://github.com/kodLite/Oasis-Theme)

I tried on a clean installation of sublime text with only ECC and Oasis and the bug is still present.

**Comment by facelessuser** [comment] 2018-05-02 13:00
Thanks. I'll do some generalized testing and post my findings afterwards. If I find a bug, I'll work on a fix.

**Comment by niosus** [comment] 2018-05-02 15:20
Thanks so much @facelessuser !

**Comment by facelessuser** [comment] 2018-05-03 05:00
This is neither an EasyClangComplete or MdPopups issue.  This is an Oasis Theme issue.  The fix is [here](https://github.com/kodLite/Oasis-Theme/commit/6121f353901440143216070163641e1929194166).  It was made on Feb 14, 2015.  But the last [release](https://github.com/kodLite/Oasis-Theme/releases) was made on May 22, 2014.

In short, the latest Oasis theme does not have the fix.  The plist lib cannot read it properly and fails. If Oasis cut a new release, it would work, but they haven't in about 4 years.  So I would manually install the latest Oasis theme yourself.

**Comment by facelessuser** [comment] 2018-05-03 05:12
I will say this though, I did not experience issues on the latest dev release.  But it does show on the latest stable release 3143.

Now I know Sublime maintains there own Python3.3.  So maybe they've backported some fixes that allows it work on the latest dev release, but on the stable branch, the error was clearly what was fixed in Oasis on Feb 14, 2015.  By applying that fix to Oasis on the stable branch, I was able to fix the issues I was seeing. The fix was not needed on the dev branch. 

So an alternative fix would be moving to the latest dev release if you have a Sublime license.

**Comment by niosus** [comment] 2018-05-03 07:04
Thanks for the info. I was expecting that it is an issue with the theme, but being no expert on sublime themes, wanted to have an opinion of someone who worked with that much more than I did. And thanks for the info on the dev release, that explains why I did not experience this issue locally on my machine which runs one.

I will close this issue now.

**Closed by niosus** 2018-05-03 07:04 UTC
Labels: blame-somebody-else, bug, cannot-reproduce
