### ISSUE TITLE
Completion takes a while (~1 second or more) to come up, and does not work for stl containers

### ISSUE THREAD

**Issue by Zouch** [niosus/EasyClangComplete#112] opened 2016-10-29 00:01 UTC
I am using sublime-text 3 on arch linux, with clang3.9, if it makes any difference.
The codebase is about ~30k lines of code. When I type a trigger key I first get the default sublime completion stuff then, about 1 second after, I finally get the clang completions.

Also if I declare, say a `std::vector<int> v;` then type `v.`, I never get completion for it. (Member variables being a std::something are completed though)

My config is the following 

```
{
    "include_dirs" :
    [
        "/usr/include",
        "$project_base_path/src",
        "/workspace/$project_name/src",
        "/usr/lib/clang/3.9.0/include",
        "/usr/include/c++/6.2.1",
        "/usr/include/qt"  // Does not look to have any impact
    ],

    "std_flag_c" : "-std=c11",
    "std_flag_cpp" : "-std=c++14",
    "search_clang_complete_file": true,
    "generate_flags_with_cmake": true,
    "errors_on_save": true,
    "triggers" : [ ".", "->", "::"],
    "use_libclang" : false,
    "verbose" : true,
    "include_file_folder" : true,
    "include_file_parent_folder" : true,
    "clang_binary" : "clang++",
    "autocomplete_all" : false,
    "use_project_specific_settings": false,
    "hide_default_completions": false,
}
```

I tried both `true` and `false` values for the following keys :

```
"autocomplete_all" ,  "generate_flags_with_cmake", "use_libclang"
```

Btw, if I set `hide_default_completions` to `true`, I do not get any completion.

The console output is the following 

```
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 32
DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 32
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 32
DEBUG:EasyClangComplete.EasyClangComplete: prefix: , locations: [1942]
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: matched trigger '.'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 1942
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.completion.bin_complete: clang command: 
clang++ -c -fsyntax-only -x c++ -std=c++14 -Xclang -code-completion-at=/tmp/EasyClangComplete/MainApplication.cpp:69:11 /tmp/EasyClangComplete/MainApplication.cpp -I "/usr/include" -I "/home/zouch/Prog/Radium-Engine/src" -I "/workspace/radium/src" -I "/home/zouch/Prog/Radium-Engine/src/MainApplication" -I "/home/zouch/Prog/Radium-Engine/src" -I "/home/zouch/Prog/Radium-Engine/Plugins/Animation/src" -DSkinning_EXPORTS -DAnimation_EXPORTS -I "/home/zouch/Prog/Radium-Engine/src/Tests/CoreTests" -isystem "/usr/include/qt/QtGui" -DQT_WIDGETS_LIB -DQT_CORE_LIB -I "/tmp/EasyClangComplete/cmake_builds/553b126e8ab7099fc2e5d7131ef6a7e4/Plugins/FancyMesh" -I "/tmp/EasyClangComplete/cmake_builds/553b126e8ab7099fc2e5d7131ef6a7e4/Plugins/Skinning" -I "/tmp/EasyClangComplete/cmake_builds/553b126e8ab7099fc2e5d7131ef6a7e4/Plugins/Animation" -isystem "/usr/include/qt/QtOpenGL" -DRA_GUIBASE_EXPORTS -I "/home/zouch/Prog/Radium-Engine/src" -isystem "/usr/include/qt/QtWidgets" -DradiumGuiBase_EXPORTS -I "/home/zouch/Prog/Radium-Engine/3rdPartyLibraries/Eigen" -I "/home/zouch/Prog/Radium-Engine/src/." -DRA_CORE_EXPORTS -DradiumCore_EXPORTS -I "/home/zouch/Prog/Radium-Engine/Plugins/Skinning/src" -I "/home/zouch/Prog/Radium-Engine/3rdPartyLibraries/Assimp/include" -DQT_OPENGL_LIB -DRA_ENGINE_EXPORTS -DFancyMesh_EXPORTS -DQT_GUI_LIB -std=gnu++14 -D_DEBUG -I "/tmp/EasyClangComplete/cmake_builds/553b126e8ab7099fc2e5d7131ef6a7e4/src" -DCORE_DEBUG -isystem "/usr/include/qt/QtCore" -isystem "/usr/lib/qt/mkspecs/linux-g++" -I "/home/zouch/Prog/Radium-Engine/Plugins/FancyMesh" -I "/home/zouch/Prog/Radium-Engine/Plugins/Animation" -isystem "/usr/include/qt" -I "/home/zouch/Prog/Radium-Engine/Plugins/Skinning" -I "/tmp/EasyClangComplete/cmake_builds/553b126e8ab7099fc2e5d7131ef6a7e4/src/Tests/CoreTests" -DQT_COMPILING_QSTRING_COMPAT_CPP -DradiumEngine_EXPORTS -I "/home/zouch/Prog/Radium-Engine/Plugins/FancyMesh/src" -I "/home/zouch/Prog/Radium-Engine/Plugins/../src"
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process finished with code: 1
DEBUG:EasyClangComplete.plugin.completion.base_complete: clang process output: 
In file included from /tmp/EasyClangComplete/MainApplication.cpp:1:
In file included from /home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.hpp:5:
In file included from /usr/include/qt/QtWidgets/QApplication:1:
In file included from /usr/include/qt/QtWidgets/qapplication.h:43:
In file included from /usr/include/qt/QtCore/qcoreapplication.h:43:
/usr/include/qt/QtCore/qglobal.h:1113:4: error: "You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC (-fPIE is not enough)."
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
   ^
In file included from /tmp/EasyClangComplete/MainApplication.cpp:33:
/home/zouch/Prog/Radium-Engine/src/MainApplication/Gui/MainWindow.hpp:5:10: fatal error: 'ui_MainWindow.h' file not found
#include "ui_MainWindow.h"
         ^
2 errors generated.
COMPLETION: a : [#int#]a
COMPLETION: b : [#int#]b
COMPLETION: Foo : Foo::
COMPLETION: operator= : [#Foo &#]operator=(<#const Foo &#>)
COMPLETION: operator= : [#Foo &#]operator=(<#Foo &&#>)
COMPLETION: ~Foo : [#void#]~Foo()

DEBUG:EasyClangComplete.plugin.completion.bin_complete: code complete done in 1.1243560314178467 seconds
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /tmp/EasyClangComplete/MainApplication.cpp:1:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.hpp:5:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /usr/include/qt/QtWidgets/QApplication:1:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /usr/include/qt/QtWidgets/qapplication.h:43:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /usr/include/qt/QtCore/qcoreapplication.h:43:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '/usr/include/qt/QtCore/qglobal.h:1113:4: error: "You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC (-fPIE is not enough)."' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '   ^' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion 'In file included from /tmp/EasyClangComplete/MainApplication.cpp:33:' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '/home/zouch/Prog/Radium-Engine/src/MainApplication/Gui/MainWindow.hpp:5:10: fatal error: 'ui_MainWindow.h' file not found' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '#include "ui_MainWindow.h"' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '         ^' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completion '2 errors generated.' did not match pattern 'COMPLETION:\s(?P<name>.*)\s:\s(?P<content>.*)'
DEBUG:EasyClangComplete.plugin.completion.bin_complete: completions: [['a\tint a', 'a'], ['b\tint b', 'b'], ['Foo\tFoo::', 'Foo::'], ['operator=\tFoo & operator=(const Foo &)', 'operator=(${1:const Foo &})'], ['operator=\tFoo & operator=(Foo &&)', 'operator=(${1:Foo &&})'], ['~Foo\tvoid ~Foo()', '~Foo()']]
DEBUG:EasyClangComplete.plugin.completion.base_complete: reload completion tooltip
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 32
DEBUG:EasyClangComplete.EasyClangComplete: prefix: , locations: [1942]
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: returning existing completions
DEBUG:EasyClangComplete.plugin.completion.base_complete: adding clang completions to default ones
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 32
DEBUG:EasyClangComplete.plugin.error_vis: removing old error regions
DEBUG:root: adding error {'col': '4', 'row': '1113', 'error': '"You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC (-fPIE is not enough)."', 'file': '/usr/include/qt/QtCore/qglobal.h'}
DEBUG:root: adding error {'col': '10', 'row': '5', 'error': "'ui_MainWindow.h' file not found", 'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/Gui/MainWindow.hpp'}
DEBUG:EasyClangComplete.plugin.error_vis: 1 error regions ready
DEBUG:EasyClangComplete.plugin.error_vis: showing error regions: []
DEBUG:EasyClangComplete.plugin.completion.lib_complete: removing TUs older than: 1800 secs.
DEBUG:EasyClangComplete.plugin.completion.lib_complete: no old TUs.
```

If it can help, here is the source code : https://github.com/AGGA-IRIT/Radium-Engine

Thanks for the help

**Comment by niosus** [comment] 2016-10-29 09:44
Do the completion times get better after you save your document a couple of times while having `use_libclang` set to `true`?

Also, there seems to be an error:
> `/home/zouch/Prog/Radium-Engine/src/MainApplication/Gui/MainWindow.hpp:5:10: fatal error: 'ui_MainWindow.h' file not found #include "ui_MainWindow.h"`

This error spawns from the fact, that you are apparently using forms for your gui and this plugin doesn't know where to search for MOC'ed headers autogenerated by qt. I have no good solution for this, so what I have ended up doing is specifying the actual project build folder as one of the `include_dirs`. This ensures that the plugin is able to find the generated headers.

Here is an example entry to `include_dirs` for one of my private projects:
```
"/home/igor/Code/catkin_ws/build/dynamics_processing/src/qt/src",
```
Note the `build` in the middle of the path. This is the path, where qt generates the ui headers. Once we get rid of this error, we can target the absence of vector completions.

**Comment by Zouch** [comment] 2016-10-29 10:24
Adding the build dir seemed to get rid of the 'ui_MainWindow.h' error and `ClangEasyComplete` does not seem to rerun cmake everytime.

I have not noticed a real difference after many saves, but it might be due to the fact that now this is the linter that looks to get a bit crazy (this is code that compiles fine).

```
DEBUG:EasyClangComplete.plugin.tools: matched trigger '->'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 2208
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.completion.lib_complete: started code complete for view 32
DEBUG:EasyClangComplete.plugin.completion.lib_complete: code complete done in 0.6349802017211914 seconds
DEBUG:EasyClangComplete.plugin.completion.lib_complete: completions: []
DEBUG:EasyClangComplete.plugin.completion.lib_complete: no completions
ERROR:EasyClangComplete.plugin.completion.compiler_variant:regex '(?P<file>.+)'.*line\s(?P<row>\d+), column\s(?P<col>\d+) failed to match location: <SourceLocation file None, line 0, column 0>
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 32
DEBUG:EasyClangComplete.plugin.error_vis: removing old error regions
DEBUG:root: adding error {'file': '/usr/include/time.h', 'col': '11', 'row': '37', 'error': "'stddef.h' file not found"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '29', 'row': '52', 'error': "no matching constructor for initialization of 'QTimer'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '21', 'row': '66', 'error': "cannot initialize a variable of type 'std::string' (aka 'int') with an lvalue of type 'const char [15]'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '35', 'row': '74', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '38', 'row': '75', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '36', 'row': '76', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '41', 'row': '77', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '81', 'error': "no matching member function for call to 'process'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '88', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '88', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '91', 'error': "invalid operands to binary expression ('std::stringstream' (aka 'int') and 'const char *')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '99', 'error': "invalid operands to binary expression ('std::stringstream' (aka 'int') and 'const char *')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '101', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '101', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '33', 'row': '101', 'error': "member reference base type 'std::stringstream' (aka 'int') is not a structure or union"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '15', 'row': '103', 'error': "member reference base type 'std::stringstream' (aka 'int') is not a structure or union"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '104', 'error': "invalid operands to binary expression ('std::stringstream' (aka 'int') and 'const char *')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '108', 'error': "invalid operands to binary expression ('std::stringstream' (aka 'int') and 'const char *')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '111', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '111', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:EasyClangComplete.plugin.error_vis: 10 error regions ready
```

I will investigate on the `stddef.h` not found, that's weird...

**Comment by Zouch** [comment] 2016-10-29 10:32
Update with properly included `/usr/lib/clang/3.9.0/include/`...
I'm running the completion with for the following here :

```
std::string foo = "bar";
foo.
```

```
DEBUG:EasyClangComplete.plugin.tools: matched trigger '.'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 2207
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.completion.lib_complete: started code complete for view 32
DEBUG:EasyClangComplete.plugin.completion.lib_complete: code complete done in 0.6918189525604248 seconds
DEBUG:EasyClangComplete.plugin.completion.lib_complete: completions: []
DEBUG:EasyClangComplete.plugin.completion.lib_complete: no completions
ERROR:EasyClangComplete.plugin.completion.compiler_variant:regex '(?P<file>.+)'.*line\s(?P<row>\d+), column\s(?P<col>\d+) failed to match location: <SourceLocation file None, line 0, column 0>
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 32
DEBUG:EasyClangComplete.plugin.error_vis: removing old error regions
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '60', 'error': "no member named 'clock_t' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '61', 'error': "no member named 'time_t' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '62', 'error': "no member named 'tm' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '64', 'error': "no member named 'clock' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '65', 'error': "no member named 'difftime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '66', 'error': "no member named 'mktime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '67', 'error': "no member named 'time' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '68', 'error': "no member named 'asctime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '69', 'error': "no member named 'ctime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '70', 'error': "no member named 'gmtime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '71', 'error': "no member named 'localtime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/ctime', 'col': '11', 'row': '72', 'error': "no member named 'strftime' in the global namespace"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/chrono', 'col': '19', 'row': '733', 'error': "no type named 'time_t' in namespace 'std'"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/chrono', 'col': '24', 'row': '741', 'error': "no type named 'time_t' in namespace 'std'"}
DEBUG:root: adding error {'file': '/usr/include/c++/6.2.1/chrono', 'col': '14', 'row': '736', 'error': "no member named 'time_t' in namespace 'std'"}
DEBUG:root: adding error {'file': '/usr/include/pthread.h', 'col': '12', 'row': '398', 'error': "unknown type name 'cpu_set_t'"}
DEBUG:root: adding error {'file': '/usr/include/pthread.h', 'col': '6', 'row': '405', 'error': "unknown type name 'cpu_set_t'"}
DEBUG:root: adding error {'file': '/usr/include/pthread.h', 'col': '14', 'row': '475', 'error': "unknown type name 'cpu_set_t'"}
DEBUG:root: adding error {'file': '/usr/include/pthread.h', 'col': '8', 'row': '480', 'error': "unknown type name 'cpu_set_t'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '29', 'row': '52', 'error': "no matching constructor for initialization of 'QTimer'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '21', 'row': '66', 'error': "variable has incomplete type 'std::string' (aka 'basic_string<char>')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '35', 'row': '74', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '38', 'row': '75', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '36', 'row': '76', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '41', 'row': '77', 'error': "no matching constructor for initialization of 'QStringList'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '16', 'row': '81', 'error': "no matching member function for call to 'process'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '88', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '88', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '27', 'row': '89', 'error': "variable has incomplete type 'std::stringstream' (aka 'basic_stringstream<char>')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '101', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '101', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '21', 'row': '103', 'error': "invalid use of incomplete type 'std::string' (aka 'basic_string<char>')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '111', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '111', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '21', 'row': '113', 'error': "invalid use of incomplete type 'std::string' (aka 'basic_string<char>')"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '117', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '117', 'error': "no member named 'Get' in 'FILELog'"}
DEBUG:root: adding error {'file': '/home/zouch/Prog/Radium-Engine/src/MainApplication/MainApplication.cpp', 'col': '9', 'row': '119', 'error': "no member named 'ReportingLevel' in 'FILELog'"}
DEBUG:EasyClangComplete.plugin.error_vis: 10 error regions ready
DEBUG:EasyClangComplete.plugin.error_vis: showing error regions: [(2154, 2165), (4082, 4089), (3792, 3798), (3792, 3798), (3838, 3845), (2412, 2417), (2418, 2427), (2544, 2555), (2710, 2721), (4068, 4077), (4068, 4077), (
```

**Comment by niosus** [comment] 2016-10-29 11:17
I have cloned the project and opened a file at random. Everything was initialized properly and I am able to autocomplete and it doesn't take much time. Seems the issue is actually in your include dirs. Try these:
```
"include_dirs" :
    [
        "/usr/include",
        "$project_base_path/src",
        "/workspace/$project_name/src",
        "/usr/lib/clang/3.9.0/include",
    ],
```

**Comment by Zouch** [comment] 2016-10-29 11:46
Don't really know what I changed but the completion seems ok. Still takes a will to come up though. 
I will do some timing to try to see where it comes from.

**Comment by niosus** [comment] 2016-10-29 11:47
The first completion will be slow as it compiles the code. Subsequent ones should be faster if you are using `"use_libclang": true`. I will close this issue for now.

**Closed by niosus** 2016-10-29 11:47 UTC
Labels: bug, cannot reproduce

**Comment by Zouch** [comment] 2016-10-29 11:57
`DEBUG:EasyClangComplete.plugin.completion.lib_complete: code complete done in 1.239201307296753 seconds`

This is not the first time the compilation is done and I am using libclang.
I'm wondering if this could be related to the 

```
DEBUG:root: adding error {'col': '4', 'row': '1113', 'file': '/usr/include/qt/QtCore/qglobal.h', 'error': 'You must build your code with position independent code if Qt was built with -reduce-relocations. '}
```

I get, thus the code keeps on compiling or something like this.
I will try with a version other than the one in the Arch repositories.

**Comment by niosus** [comment] 2016-10-29 12:21
Seems that this is actually the cause. But I have never seen an error like this before. Feel free to reopen this issue if you feel that something can be improved in the plugin to avoid problems like this.

**Comment by Zouch** [comment] 2016-10-29 14:25
It looks like the fixes are to add `-fPIC` or `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` both in the `CMakeLists.txt`.

I did that but I still get the error from `EasyClangComplete` as if it was ignoring this kind of flags from cmake.
