### ISSUE TITLE
Show full error output in the console and navigate to next error

### ISSUE THREAD

**Issue by saagarjha** [niosus/EasyClangComplete#350] opened 2017-11-06 21:41 UTC
# Please do this before submitting: #
- [X] check for already solved issues
- [X] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `Sublime Text Version 3.0, Build 3143`
- which system are you on: `macOS High Sierra 10.13.2 Beta (17C60c)`

When building a C++ file, Sublime Text shows similar "phantoms" in a similar way as EasyClangComplete does (albeit with a smaller close button). In addition, it opens the console so that it's possible to see the full compiler output (in addition to the snippet shown inline), which can be helpful when trying to diagnose issues. I was wondering if it would be possible for EasyClangComplete to have this feature as well.

**Comment by niosus** [comment] 2017-11-07 03:34
Hey, thanks for your suggestion. Yes, I had plans to show all errors. I am currently quite time constrained, but I will implement it at some point.

**Comment by saagarjha** [comment] 2017-11-07 09:04
Cool. I look forward to seeing this implemented!

**Comment by niosus** [comment] 2017-12-14 17:04
The PR has been merged to master, thus closing this.

**Closed by niosus** 2017-12-14 17:04 UTC
Labels: enhancement

**Comment by saagarjha** [comment] 2017-12-14 20:11
Hmm…I was looking for something more along the lines of what happens when you run a build from Sublime Text–the console will pop up with the compile command and the full error from the compiler, along with the compiler invocation, is shown. Is this something you're planning on adding?

**Comment by niosus** [comment] 2017-12-15 10:22
Yeah, I was considering that, but that always feels gimmicky to me. Also, adding this should now be quite easy. The issue is that libclang does not provide a full error message on its own, so there is really no additional information that I could show and the current way seems to have a nice navigation across errors to it.
