### ISSUE TITLE
Unknown type and file not found errors

### ISSUE THREAD

**Issue by raymusmunt** [niosus/EasyClangComplete#189] opened 2017-01-06 14:22 UTC
How can I fix these unknown type and file not found errors ?

![screenshot 2017-01-06 14 19 41](https://cloud.githubusercontent.com/assets/9137896/21720478/55ff70a8-d41b-11e6-9f85-14f2ac303264.png)

My .clang_compete file contains entries that look like this :
` -I/Users/user/.platformio/lib/FastLED_ID126`

**Comment by niosus** [comment] 2017-01-06 15:17
It is hard to say what exactly is wrong. Make sure that all the headers can be found under `/Users/user/.platformio/lib/FastLED_ID126` or use a build system like CMake - it will handle this for you.

Anyway, this is not a bug of the plugin, so I will close this issue for now. In case you need some help, I would need access to the project in some way. Otherwise it is hard to say anything.

**Closed by niosus** 2017-01-06 15:17 UTC
