### ISSUE TITLE
Feature request: Auto-completion within header files

### ISSUE THREAD

**Issue by mhoeher** [niosus/EasyClangComplete#353] opened 2017-11-10 11:21 UTC
It seems that ECC currently only provides auto-completion within C/C++ implementation (`*.c`/`*.cpp`) files (at least when using `compile_commands.json`). However, especially when using template programming, one often also has to write a lot of code in header files. There, no auto-completion seems to be available.

It would be cool if ECC could support auto-completion in headers as well. I know that this might not be trivial, because headers are typically included by several compilation units and hence are likely to run through different settings (usually different defines but also different include paths). Plus, the `compile_commands.json` file has no entries for headers but only implementation files. However, I guess it is possible to implement some heuristic to find a matching file in the compile definitions and use its configuration to auto-complete also a header.

Thanks for considering :-)

**Comment by niosus** [comment] 2017-11-10 17:23
Autocompletion should be available in those files too. I would bet on some configuration issue if this does not work for you. Could you set up a test project to illustrate the issue? I use comletion in headers every day and it works well. The only other option apart from this being a configuration issue I can think of is that the type is not known in the translation unit you are compiling. In this case there is nothing I can fix here.

**Comment by mhoeher** [comment] 2017-11-10 23:41
Wow, you are right 8-)
I just set up a small toy project and there autocompletion is working fine in the header file.

Unfortunately, I do not have access to the project in which I encounter the (non-working) autocompletion right now (will try to look into this next Monday when I am back at work). The project is a quite large C/C++ project targeting an embedded platform. Could that possible be a cause for the issue?

Do you have any hints on how to debug the issue otherwise? Are there any requirements for the naming of the header files (e.g. header files must be in the same directory as the source files)?

For reference, I am attaching my sample project which I set up locally:

[cmake-ecc-header-autocompletion.tar.gz](https://github.com/niosus/EasyClangComplete/files/1463010/cmake-ecc-header-autocompletion.tar.gz)

I used the following to configure and build:

```bash
mkdir build
cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
make
```
In addition, I created a symlink to the `compile_commands.json` file in the project root (that's similar to the setup used in the project where autocompletion is not working):

```bash
cd ..
ln -s build/compile_commands.json
```

With that, autocompletion works fine in both `test.hpp` and `test.cpp`. What is a bit strange is that some errors are shown in `main.cpp` although the build runs through fine.

**Comment by mhoeher** [comment] 2017-11-14 09:19
And it's me again.

Back at work, I tested with the project I have the issues with. Auto-completion works fine in the source files, but as soon as I edit a header file, I get no auto-completion and - looking into the console - I get these kinds of errors:

```
[ECC:ERROR  ]: error while completing view /home/mhoeher/Projects/app/somemod/inc/someheader.hpp: 'NoneType' object has no attribute 'codeComplete'
```

Is there anything I can do to get more debug output?

Additionally, how are the flags for the header files retrieved? In the project I am working on we have the following structure:

* The project is divided into several (static) libraries and apps.
* Each library and app has its own directory.
* Each of these directories in turn has the following structure:
    * `inc/` - includes the module header files
    * `src/` - includes the module source files
    * Other subdirectories, depending on what the module requires.

Could that lead to issues (e.g. is it required that header and source files are stored within the very same directory)?

**Comment by niosus** [comment] 2017-12-07 11:01
Sorry for a big delay. Had no time at all to look into it. Now it should be much better :)
This seems to me still as a configuration issue. If you manually specify the folders for includes you need to know what you are doing, otherwise just use cmake or provide a compilation database generated with some tool and the plugin should be able to do the rest.

If you need more help with this, try to run it again setting `verbose` setting to `true` and copy over the console output from the moment you start sublime text until you see no completion.

**Comment by mhoeher** [comment] 2017-12-07 13:02
No problem, just take your time ;-)

First of all: I am using cmake. It generates the `compile_commands.json` file which is correctly picked up by ECC ;-)

Regarding logs - here you go: [ecc_log.txt](https://github.com/niosus/EasyClangComplete/files/1539030/ecc_log.txt)

Disclaimer: I edited the log. There are two lines where there were a lot of compile flags, which of course disclose a lot about the project this is taken from. As it is a closed source project (which I don't own) I cannot openly share all details here.

I checked the arguments and it seems that they are basically the union of all arguments passed to the different source files? I guess this might cause trouble (some of the defines and probably also some include paths definitely must be used only locally in their respective modules).

I tried to debug this by copying the argument list and in a Python shell I did the following:

```python
>>> args = # <Paste> the long argument list from the log...
>>> from subprocess import run
>>> res = run(["clang++"] + args + ["common/trace/inc/traceservice.hpp"])
clang: error: unknown argument: '-mlongcalls'
clang: error: unknown argument: '-mno-serialize-volatile'
clang: error: no such file or directory: 'rtosconfig.h'
```
The interesting part is that the path where the missing file is stored *is* actually passed to the compiler via the command flags.

I further tried to remove the `-m` flags and manually add the path to the missing header:

```python
>>> args.remove("-mno-serialize-volatile")
>>> args.remove("-mlongcalls")
>>> res = run(["clang++", "-I./rtos/inc/"] + args + ["common/trace/inc/traceservice.hpp"])
clang: error: no such file or directory: 'rtosconfig.h'
```

So for some reason `clang++` is unable to locate the header :-(

I also repeated the test with `clang++` substituted by the compiler for the target platform, with basically the same result. However, for the appropriate source file (in that case `traceservice.cpp`) ECC works just fine out of the box.

**Comment by niosus** [comment] 2017-12-07 13:33
This is definitely an error with flags as shown by this line in the log:
```
[ECC:ERROR]:[lib_complete.py]:[parse_tu]:[Thread-5]: error while compiling: Error parsing translation unit.
```
And yes, you're right, in your case, all the flags will be merged together as in case of a header file we have no way of knowing the actual flags for it. The logic there is to just try to find an entry with the same file name stripping the extension. As the path is different (because of "include") folder the plugin cannot find a corresponding implementation file in the database and defaults to merging all flags from all entries together as a closest sane alternative.

I don't know what causes the issue when merging all flags together without having a look at the code unfortunately :( I understand that you cannot share it easily, but maybe the above will allow you to create a small example that reproduces the issue. Also, you already had a project before. You can try to add the flags that clang reports as unrecognized there, they might be causing the issue too. I don't know how libclang handles flags that it does not know about.

**Comment by mhoeher** [comment] 2017-12-07 14:16
Regarding your last point: Those flags seem to be just ignored. I just checked my `compile_commands.json` for the source file belonging to the header file I did the analysis for. For that source file both `-m` switches are present - and code completion works just fine ;-)

I tried to reproduce the issue, however, it seems to be not that easy :( At least I managed to construct a case where:

* Compilation via CMake/Make succeeds but
* ECC (checking the file `main.hpp` in the attached example) reports an error.

See here: [st3_ecc_header_completion.tar.gz](https://github.com/niosus/EasyClangComplete/files/1539338/st3_ecc_header_completion.tar.gz)

Do you think it would be possible to implement some more advanced heuristic to find the "right" compile flags for a header file? Like:

1. Just check for a file with the same name with extension removed (like it is now).
2. Search for a CPP file with the same file name but in the directory `../inc`.
3. If that yields no result, fall back to merge all flags and use this.

I could even imagine to make point 2 more powerful, by allowing the user to specify a list of "lookup substitutions" which can contain certain (predefined) template variables, like this:

```json
{
    "header_to_source_lookups": [
        "../inc/{BASENAME}.cpp",
        "../inc/{BASENAME}.cxx",
        "../../lib_ifc/{BASENAME}.c",
        "../extra/{BASENAME}.cpp",
        "{FILENAME}.someexoticextension"
    ]
}
```
That way I guess even more complex projects should work just fine. What do you think?

**Comment by niosus** [comment] 2017-12-07 15:17
Yeah, I was thinking about this since my last message. The issue with heuristics is that it is hard to write a proper one. We can default to searching in `inc`, `include`, `headers` (all real world names seen in real projects) and allow the user to define his own naming scheme. Another issue is to find out *which* folder to replace with this `headers` folder. Also *if* it should be replaced. I've seen people using smth like `src/include` for headers location.

Overall, I like your idea with the substitution and might spend some time to implement it soon as it would make configuration slightly easier.

**Comment by mhoeher** [comment] 2017-12-07 16:11
That'd definitely be cool :-)

If it helps you, I could also try to implement this feature on my side (at least I obviously have a good test project at hand). I have some experience with Python, but not with writing Sublime plugins, so probably have to look into getting things set up first.

**Comment by mhoeher** [comment] 2017-12-08 09:11
Okay, I tried to implement the discussed header-to-source lookup. I tried my implementation with both the initial project I discovered the issue with as well as the dummy one I uploaded yesterday and both seem to work fine now.

Basically, with the changes one now:

* Defines a list of globbing expressions relative to the current header file's directory.
* These expressions may contain pre-defined placeholders (`basename`, `stamp` and `ext`).
* These globbing expressions are used to retrieved a list of **related** files.
* The first related file that is found in the compilation DB is then used as flags source for the header.

If none of the found related files is found in the DB, we still use the merged flags.

By the way: I removed the "special" handling which was in before that removed the file name extension:

* The same behavior is achieved via carefully chosen lookup templates (with the default templates doing so) and
* I think "blind" removal of the file name extension could also introduce issues (imagine one has a directory which contains both `foo.cpp` and `foo.c`, which might be unusual but not impossible - IIRC I've already seen such cases in the past...).

**Comment by niosus** [comment] 2017-12-14 17:03
I have pushed the PR to master, thus closing this issue.

**Closed by niosus** 2017-12-14 17:03 UTC
Labels: configuration-issue, enhancement

**Comment by papadokolos** [comment] 2018-01-27 11:13
It seems like you already got this figured out, but I think that [this interesting project (compdb)](https://github.com/Sarcasm/compdb) might still be relevant to you. As far as I understand, this project is capable of manipulating an existing `compile_commands.json` file and adding header file entries to it.

Since it is written in python, it should be simple to add it as a dependency, right? (Ofcouse only in case it is needed).
