### ISSUE TITLE
Deadlock if close the view while error_vis generating error messages.

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#99] opened 2016-10-19 23:24 UTC
Assuming error_on_save = true, and your code has too many errors. 
Open a C++ source code file, move focus to that view, then close this view by Command + W while compiling and generating error messages (showing in verbose mode). Sublime text will freeze, except kill the plugin_host precess.

**Comment by niosus** [comment] 2016-10-21 09:20
Good catch. I will try to look into this over the weekend. There are still some crashes around. Just didn't have the time to find them and solve them.

Feel free to open a pull request if you know how to fix this. This will save me a lot of time and will ensure the fix lands faster as currently my day-work life proves to be quite busy.

**Comment by david9991** [comment] 2016-10-21 12:16
@niosus I think use on_xxxxx_async() with Rlock is not a good idea. I guess the thread which running the on_activated_async() -> completer.init() will be cancelled immediately when the View is closed, self.rlock has no chance to be released, so the on_close() event will be blocked by the RLock in the completer.remove() forever.

**Comment by david9991** [comment] 2016-10-21 12:23
I have tried 3 ways to fix this issue will work: 1. comment the RLock in completer.remove(). 2. comment the RLock() in completer.init(). 3. Change on_activated_async(), on_post_save() to on_activated(), on_post_save(). So it can prove something I said.

**Comment by niosus** [comment] 2016-10-22 16:25
Ok, confirmed. I will be looking into this today or tomorrow.

**Comment by niosus** [comment] 2016-10-22 16:42
The only thing I am not getting is why it doesn't crash when I disable error visualization. If we don't show errors, then the lock is acquired for compilation, then another thread tries to close the view, fails to acquire the lock, blocks there and continues with closing the view as soon as the compilation is finished.

This does not happen if the error visualization is there, which leads me to the thought, that there is some exception happening (like the absence of the view to show errors in etc.) that prevents the lock to be released (although, it should still work, when acquiring the lock with `with` statement).

**Comment by david9991** [comment] 2016-10-24 08:18
I tried to put a 'self.rlock.release()' before 'with self.rlock:' in remove() function, it works. I think you don't need to wait anything in on_close() event, because the View is already gone before on_close() event called.

The traceback show us it stuck at sem_wait(), and seems the thing that should post the semaphore was dead.

> 2537 edit_window::close()  (in Sublime Text) + 338  [0x105109646]
>     +                                     2537 edit_window::close_file()  (in Sublime Text) + 98  [0x105109490]
>     +                                       2537 sheet_list::remove_sheet(SP<sheet>, unsigned int)  (in Sublime Text) + 1404  [0x10518ccfe]
>     +                                         2537 edit_window::on_post_close(sheet*)  (in Sublime Text) + 110  [0x105108300]
>     +                                           2537 plugin_on_close(unsigned int)  (in Sublime Text) + 20  [0x10515d9ca]
>     +                                             2537 int send_helper<int>::send_message<13u, unsigned int>(unsigned int const&)  (in Sublime > Text) + 219  [0x10516ecb7]
>     +                                               2537 void wait_for_reply<int>(reply_entry*, int*)  (in Sublime Text) + 161  [0x10517c630]
>     +                                                 2537 shm_channel::read_message(string_buffer*, int)  (in Sublime Text) + 48  [> 0x10535c13a]
>     +                                                   2537 shm_channel::read_bytes(char*, unsigned long, int)  (in Sublime Text) + 53  [> 0x10535c055]
>     +                                                     2537 sem_wait  (in libsystem_kernel.dylib) + 10  [0x7fffba6b6416]

**Comment by niosus** [comment] 2016-10-24 08:29
I have to think about it. Thanks for the suggestions. Adding `self.rlock.release()` feels quite hacky even though, the justification seems to be sound.

**Comment by niosus** [comment] 2016-10-29 16:45
Should be fixed in commit 1c3657b757ca4ff7e135e31ca865ee34610d0168
I will be testing this over the weekend and if nothing goes wrong will release it tomorrow.
I have removed showing errors when completing for now, so they are only shown when the file is saved.

**Comment by david9991** [comment] 2016-10-30 01:27
I have tested 1c3657b, it doesn't work for me.

**Comment by niosus** [comment] 2016-10-30 08:20
Hey @david9991 can you please elaborate more? What have you tested and what does not work for you?

**Comment by david9991** [comment] 2016-10-30 08:36
Just same like what I did before. 
```
"errors_on_save": true,
"use_libclang" : true,
"verbose" : true,
```
And open a large C++ file, comment some headers to produce many errors.
Close this file and reopen it, then move focus to that view, it'll be compiled and error message came out, and close the view immediately while error being generated, it will stuck there.

**Comment by niosus** [comment] 2016-10-30 08:49
Oh. You're right. So not solved then yet.

**Comment by david9991** [comment] 2016-10-30 09:09
I think we are not the only guy met the issue:
https://forum.sublimetext.com/t/st3-bug-inaccessible-view-properties-in-async-event/9857/6

**Comment by niosus** [comment] 2016-10-30 09:25
Even if this is the same issue, I still fail to see why the lock is never released...

**Comment by niosus** [comment] 2016-10-30 10:31
This should fix it. I have changed the mechanism behind the translation unit cleanup. Now it is not happening in the main thread, so the thread will not block under any circumstances. In addition to that I have added some error handling to catch those exceptions happening while working on a closed view.

**Comment by david9991** [comment] 2016-10-30 10:51
Yes, no more freeze but error occurs.

```
DEBUG:EasyClangComplete.EasyClangComplete: closing view 58
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
DEBUG:EasyClangComplete.plugin.completion.lib_complete: removing translation unit for view id: 58
DEBUG:EasyClangComplete.EasyClangComplete: removed completer for id: 58
    callback.on_activated_async(v)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 121, in on_activated_async
    self.completer.init(view, self.settings)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/completion/lib_complete.py", line 213, in init
    self.show_errors(view, self.TUs[v_id].tu().diagnostics)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/completion/base_complete.py", line 168, in show_errors
    self.error_vis.generate(view, errors)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/error_vis.py", line 43, in generate
    self.add_error(view, error)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/error_vis.py", line 64, in add_error
    if row in self.err_regions[view.buffer_id()]:
KeyError: 0
```

**Comment by david9991** [comment] 2016-10-30 10:55
I think it will be OK after exceptions be handled. :)

**Comment by niosus** [comment] 2016-10-30 11:00
It will be hard to fix all of them as we never know where exactly the code will stop as it is asynchronous, but I have added `KeyError` as a type we want to handle. Maybe just catch any exception here is a good idea. Don't have final opinion on this yet.

**Closed** 2016-10-30 22:19 UTC
Labels: bug
