### ISSUE TITLE
Trigger auto-complete in the middle of words

### ISSUE THREAD

**Issue by merlinthered** [niosus/EasyClangComplete#62] opened 2016-08-01 09:07 UTC
Hi and thanks for this awesome plugin. It goes a long way to making Sublime Text a viable choice for C++ development.

I have tried the plugin for a few hours now and I like what it's doing. What I don't like though is that I have to type one of the triggers ., :: or -> to initiate completion. Oftentimes I find myself in the situation of being in the middle of a word and I would like to autocomplete the rest of it. Or I want to change the function of a class I'm calling, so I delete the function name (or part of it) and hit Ctrl+Space, as I'm used to from other IDEs. I don't know if anybody else has this problem, but I find it kind of annyoing to have to re-type the trigger in order to get auto-completion.

Is there a chance we could get a trigger for starting auto-completion anywhere? It would parse back from the current cursor position until it finds a trigger, and then behave as if you had just typed that trigger and then typed the letters between the trigger and the cursor as a search term. Bonus points if upon choosing an autocomplete option, it replaces the whole word the trigger was placed in, instead of just the portion before the cursor. Implementing this would make this plugin behave even more like one of the major IDEs.

**Comment by niosus** [comment] 2016-08-01 12:36
Yep, I have though about this. I think it should be relatively easy to implement. Basically, I just need to trigger the thing. It is irrelevant if there is some trigger present as clang should still be able to parse the code from any place. So I just need to add an action on <kbd>Ctrl</kbd>+<kbd>Space</kbd>

**Comment by merlinthered** [comment] 2016-08-01 14:27
Nice. This will hopefully also enable autocomplete of functions and variables in the local scope, where you don't have an object name to use one of the triggers on. Right now, if I want to call a member function from within a class I have to type this-> to get autocompletion. If I want to call a function that doesn't belong to a class, I'm completely out of luck.

Clang will probably not use the same fuzzy search that Sublime uses though. I imagine it would be cool if I could type `object.sfn` and then hit <kbd>Ctrl</kbd>+<kbd>Space</kbd>, which would autocomplete to `someFunctionName()`.

Btw.: Do you know if clang can also complete paths in `#include` statements?

**Comment by niosus** [comment] 2016-08-02 12:12
All I know about includes is that YouCompleteMe can do that on vim. But let's see when I add the trigger.

**Comment by merlinthered** [comment] 2016-08-05 08:27
I just stumbled upon this answer on stackoverflow:
http://stackoverflow.com/a/15878799/2393043

Apparently code completion is meant to be triggered at ., ->, :: and so on, and the client is responsible for filtering the results via the characters already typed after the trigger.

**Comment by niosus** [comment] 2016-08-09 09:35
Oh, right! I remember seeing this some time ago. So this answers the questions about whether it is possible to complete at any arbitrary point of code.

Actually you can have a feeling of this if you enable `autocomplete_all: true` in the settings. Then it will try to complete on any position in the file.

**Comment by niosus** [comment] 2016-08-29 08:46
It seems that this is not possible at the moment, so I will close this issue for now. Feel free to reopen it if you find a way.

**Comment by rchl** [comment] 2016-08-29 10:05
Might not be wise to trigger completion in the middle of the words, but what about triggering it on word boundary (simplifying a bit here)? So basically when you start typing something on a blank line line it would provide all possible suggestions? I guess there would be a lot of them, but maybe it wouldn't be too bad performance wise. I think SublimeClang does something like that and it works fine.

**Comment by niosus** [comment] 2016-08-29 10:12
That would be nice. At some point I will probably look how other plugins do it, because now I have no idea how to trigger this :)

**Comment by merlinthered** [comment] 2016-08-29 10:45
This is currently the issue I am most interested in. If I find the time, I will look into it.

@rchl:
> So basically when you start typing something on a blank line line it would provide all possible suggestions?

This is something that always annoyed me in old versions of Visual Studio. If you start showing all possible suggestions, it only makes sense when they are ordered in a meaningful way. E.g. from local to global scope, and macros last. I'm not sure if clang does this already, and we probably can't do it ourselves without a lot of effort. In any case, completion should only be triggered automatically at locations where some context info is already available, but there should also be a manual trigger (such as ctrl+space).

**Comment by rchl** [comment] 2016-09-20 14:13
I've re-read whole this bug and I'm not sure what it is about anymore. Apparently triggering at autocomplete is already possible with `autocomplete_all: true` setting and it works fine for me. So is this bug about just improving the behavior? Like for example prioritizing local scope members/variables before other suggestions (not sure if possible)?

**Comment by niosus** [comment] 2016-09-21 20:14
I guess the idea was to not trigger the completions after every letter, but to have it triggered on triggers, while having a possiblity to trigger it in any point with <kbd>Ctrl</kbd> + <kbd>Space</kbd> and it kinda makes sense to have this behavior.

**Comment by merlinthered** [comment] 2016-09-22 07:35
Correct. Having completions pop up at every letter I type would be kind of annoying for me. The use case I have in mind specifically is when the auto completion is canceled because I mistyped a letter and there are no matches left because of this. This happens kind of often to me. In that case, I would like to correct my mistake and re-open the completions panel without having to delete everything up to the last trigger. If it would then also insert the completion automatically if it is the only remaining possibility, that would be even better.

**Comment by niosus** [comment] 2016-09-25 17:57
So. It is already possible. The problem is that the default key binding for completion is not bound to <kbd>Ctrl</kbd>+<kbd>Space</kbd> on all systems. At least on linux it is by default <kbd>Alt</kbd>+<kbd>/</kbd>. So if you have smth like: `std::` written and our cursor is right at the end of `::` and the completions are not shown we can press the key combination and they will appear.

Now I understand, that you would want something like this. 
1. If you have mistyped and written `std::vecr`, you want to delete the last character to `std::vec` and then press some key combination to generate completions. 
2. being in the beginning of the line, you want to press key combination to get names of the classes and variables and what not available.

Am I right?

I believe this is all possible. To enable this, we must look to the beginning of the word for some completion trigger. If it there, we want completions, if not, then not. Also we will need to change the behavior on triggers I guess, as now you will not get any completions in the second case because there is no completion trigger before the cursor. 

This is also partially relevant for #57

**Comment by merlinthered** [comment] 2016-09-27 07:05
Partially correct. I also want to have completions when there is no trigger. Imagine I want to call a function or refer to a variable. Right now, I have to prefix free functions with `::` to get completions. That's not ideal.  I don't even know if I can do the same for variables e.g. in the current scope. The Sublime default autocompletion helps with variables, but it can't distinguish which variables are in scope and which aren't. For functions it's near useless as it doesn't know the signature.

<kbd>Alt</kbd>+<kbd>anything</kbd> is not a good choice for any key combo on Linux, because in most window managers, all sorts of <kbd>Alt</kbd> combinations are bound to window-related operations (resize, move, open menu etc.). On my Ubuntu machine, when I press <kbd>Alt</kbd>, the window's menu bar is selected. <kbd>Alt</kbd>+<kbd>/</kbd> does nothing for me.

**Comment by rchl** [comment] 2016-09-27 07:15
- If `hide_default_completions` is `false` (the default) then it's easy to trigger clang completions at any point[*] as pressing <kbd>ctrl</kbd>+<kbd>space</kbd> 99% of the time opens completion popup with default completions and that triggers the plugin completions.
- If `hide_default_completions` is `true` then this not longer works so in that case the plugin itself would have to trigger completions itself.
- If `hide_default_completions` is `false` but there are no default completions to show (which happens rarely), it's also not possible to trigger plugin completions at that point.

That might be obvious, but I just wanted to point it out anyway. We should just make sure that both cases are tested and that the shortcuts don't try to override themselves in unexpected ways.

[*] At least on Windows, if <kbd>alt</kbd>+<kbd>/</kbd> doesn't seem to work on Linux then it might be different there.

**Comment by rchl** [comment] 2016-09-27 07:40
Hmm, maybe my comment wasn't entirely accurate. There is also `autocomplete_all` in play here...

**Comment by Jo2003** [comment] 2016-10-17 10:19
Is there any progress an this enhancement? the_autocomplete_all_ setting slows down sublime so I don't want to have it triggered on every character. 

Many thanks for such a useful plugin!

**Comment by niosus** [comment] 2016-10-24 18:28
There is currently no progress on this one. Bugs are of higher priority and unfortunately I fail to allocate enough time for everything because of work. But I hope that eventually I will reach the point when I will implement this :) Anyway, the pull request are very welcome if any of you guys would be willing to contribute.

**Comment by niosus** [comment] 2016-10-29 16:45
Should be fixed in commit 1c3657b757ca4ff7e135e31ca865ee34610d0168
I will be testing this over the weekend and if nothing goes wrong will release it tomorrow. Feel free to give it a try. It is in the `better_completions` branch.

**Closed** 2016-10-29 21:34 UTC
Labels: enhancement

**Comment by jdumas** [comment] 2017-04-28 16:21
Hi there,

Is this issue fixed now? I was looking for a way to trigger autocompletion manually on a new line (via a shortcut such as <kbd>Ctrl+Space</kbd>), e.g. to access the member variables of a class `Foo` when I'm implementing  a method `Foo::bar`. There is no "trigger" in front of the variable starting the line so the autocompletion doesn't activate. Setting `"autocomplete_all": true` works, but then everything becomes super slow, so I would prefer to activate it manually via a keyboard shortcut.

**Comment by niosus** [comment] 2017-04-28 16:50
It works for me:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/1893598/25538539/6b68ad44-2c43-11e7-800f-07dbee02df95.gif)

Mind that if you're on Linux, then the sublime's default autocompletion trigger keybinding is: <kbd>Alt</kbd>+<kbd>/</kbd>

**Comment by jdumas** [comment] 2017-04-28 17:38
Well for me it says `DEBUG:EasyClangComplete.EasyClangComplete: completion not needed` in the console when I type this shortcut =/

In your example, it would complete `printf`, but not `arg|` for example. The other typical case that doesn't work for me is this one:

```cpp
class MyClass {
	int m_Member;
	void bar(int a);
};

void MyClass::bar(int a) {
	m_Memb|
}
```

I have the following settings enabled:

```json
{
	"c_flags" : [],
	"cpp_flags" : [],
	"use_libclang" : true,
	"verbose" : true,
	"hide_default_completions": true,
	"triggers" : [ ".", "->", "::", " "],
	"use_libclang_caching": false,
}
```

**Comment by detly** [comment] 2019-03-13 21:36
> If I press ctrl+space just the build in sublime autocomplete pop up.

Same here! Console shows:

```text
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: completion not needed
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: showing default completions
```
