### ISSUE TITLE
use default autocomplete

### ISSUE THREAD

**Issue by simonhaenisch** [niosus/EasyClangComplete#15] opened 2016-05-25 13:16 UTC
When this plugin is enabled, is there a way to still have the default Sublime Text autocomplete for example for variable names?

**Comment by niosus** [comment] 2016-05-25 16:04
Hey @simonhaenisch 

Just to clarify. Is it some specific behavior you are facing or is it just a question? This plugin should only get active when you use any of the autocompletion triggers. Otherwise sublime should be using the default autocompletion engine. 

Please clarify (best with example) if I got you wrong.

**Comment by simonhaenisch** [comment] 2016-05-25 20:37
Hey @niosus, thanks for your reply. My problem is that I only get default autocompletions (i.e. variable names) if I disable the EasyClangComplete plugin. It sounds like that isn't the case for you, so maybe it's got something to do with my setup. I am not on my Windows work pc until tomorrow, so I can't take a look right now. I have set `autocomplete_triggers` in c++ syntax specific settings, but they differ a little from the ones in the readme, maybe it has something to do with that. Or maybe it is a Windows/non-libclang related issue... I will let you know what I can find out tomorrow.

**Comment by niosus** [comment] 2016-05-25 20:55
Yeah, sure, just be as specific as possible. I will try to nail the issue down as soon as I have more info.

Also, if you have time, you can try to browse the code and put some print statement in front of returns in `on_query_completion` function in `EasyClangCompleter.py` and see when it triggers.

For now I have no idea what can cause the issue, but let's see how your full setup looks like.

**Comment by niosus** [comment] 2016-05-25 21:09
Just checked on my machine while using clang binary (this is the method you are using by default on windows) and the completions for variables is fine. Probably the issue is in the settings. Can you try the ones suggested in the readme?

**Comment by simonhaenisch** [comment] 2016-05-27 11:20
I just checked my `auto_complete_triggers` settings and they already were like in the readme. I then tried disabling all other packages, but that didn't help either. I also upgraded to your latest version and tried reinstalling it via package control. And I tried using default settings.

I can't get any default completions with EasyClangComplete enabled. As soon as I disable the package I get default completions again. When I use the `verbose` option, I get `on_modified_async view id #` and `on_query_completions view id #` in the console after each keypress.

I'll try your debugging approch with print statements.

**Comment by simonhaenisch** [comment] 2016-05-27 11:46
I found the problem, it's in `EasyClangComplete.py:235`:

```python
# send empty completion and forbid to show other things
completions = []
return (completions, sublime.INHIBIT_WORD_COMPLETIONS)
```

The fix is to change completions to include an empty string:

```python
completions = [""]
```

Maybe Windows handles this differently or we have a different internal python version?

I use ST Build 3114 and my `sys.version` output in ST console is:
```
3.3.6 (default, May 10 2016, 15:30:46) [MSC v.1600 64 bit (AMD64)]
```

If it also works for you with the empty string on Linux, then this should also be changed in line 248 (I don't know where else it occurs).

**Comment by niosus** [comment] 2016-05-27 11:52
Hm, these lines were there for the reason, but now I think there is no need for them. I guess one can also just write `return None` instead and it should work for you. Can you check it? 

I will test the change either today night or on the weekend. Thanks for your time :)

**Comment by simonhaenisch** [comment] 2016-05-27 11:52
btw this is what [docs.sublimetext.info](http://docs.sublimetext.info/en/latest/reference/api.html) says about `sublime.INIBIT_WORD_COMPLETIONS`:

> Prevents Sublime Text from adding its word completions to the completion list after all plugins have been processed. This consists of any word in the current document that is longer than 3 characters.

I don't really get how it is used here...

**Comment by simonhaenisch** [comment] 2016-05-27 11:54
Yeah `return(None)` works as well

**Comment by niosus** [comment] 2016-05-27 12:03
I wanted to remove all completions if something does not satisfy the conditions that the plugin needs (like extension of the file or that the caret is actually positioned after the trigger symbol like `->`). This may be a bad decision. At least it seems like it now. Let us see how it works out for me if I use `None` instead. There may have been a reason why I did it this way, but I don't remember it now :)

**Comment by niosus** [comment] 2016-05-27 18:48
@simonhaenisch I have just pushed the changes discussed in this thread. If you are cloning my repo - you can see it from now on. If not, you will probably have to wait till tomorrow. I want to close the issue #18 before I put the new version out. I am starting it now.

I will close this issue for now. If the described behavior will still persist after you get the update to version 1.0.9 - feel free to reopen it.

**Closed by niosus** 2016-05-27 18:48 UTC
Labels: bug

**Comment by niosus** [comment] 2016-05-27 18:51
ignore my last actions :) Mixed up the browser tab :)
