### ISSUE TITLE
Issue with Clang 3.6

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#507] opened 2018-09-25 06:21 UTC
I take the same code as an example:

```
#define TEST_DEF __attribute__((__packed__))

typedef struct {
    int a;
} a_t;

int main(void) {
    a_t aa = { .a = 2 };
}
```

With Clang 5.0.0 everything is working fine. If i use Clang 3.6 (which is the default version in our system), I get an Python exception in the console, when hovering over a type

Log: [https://pastebin.com/qii7naXd](https://pastebin.com/qii7naXd)

- Sublime Text version: 3176
- Which system are you on: suse 11
- Clang version: 3.6

**Comment by niosus** [comment] 2018-09-25 07:08
This looks weird. I will copy the relevant part of the log here:
```
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
Package Control: Skipping automatic upgrade, last run at 2018-09-25 08:15:53, next run at 2018-09-25 09:15:53 or after
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-6]: config exists for view: 28
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-6]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7ffff4bf22d0>
exception calling callback for <Future at 0x7ffff4c07350 state=finished raised ArgumentError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/EasyClangComplete.py", line 408, in info_finished
    (tooltip_request, current_popup) = future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/plugin/view_config.py", line 511, in trigger_info
    return config.completer.info(tooltip_request, settings)
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/plugin/completion/lib_complete.py", line 281, in info
    self.tu, self.tu.get_location(view.file_name(), (row, col)))
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/plugin/clang/cindex36.py", line 2387, in get_location
    f = self.get_file(filename)
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/plugin/clang/cindex36.py", line 2376, in get_file
    return File.from_name(self, filename)
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Packages/EasyClangComplete/plugin/clang/cindex36.py", line 2574, in from_name
    return File(conf.lib.clang_getFile(translation_unit, file_name))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

It seems that clang is correctly found on your system, but then something strange is happening. On my system, everything seems to be working. In your case, it seems that the file does not have a name as the plugin thinks it is `None`. Can you tell me exactly what you are doing since the start of sublime text till you get an error? Even better would be a small screen capture.

**Comment by schreda** [comment] 2018-09-25 08:08
I made a screen capture for you:
[https://schreda.com/nextcloud/index.php/s/4HXQ4tSFyHHqxKJ](https://schreda.com/nextcloud/index.php/s/4HXQ4tSFyHHqxKJ)

**Comment by niosus** [comment] 2018-09-25 08:35
Ok, I got the issue, but I still don't really understand what is going on. I mean, it can be that something is wrong with the old bindings or smth else in our communication with clang, but at this point, it is hard to test and I don't have enough time to support all versions properly. Sorry about that.

**Comment by niosus** [comment] 2018-09-25 08:36
Again, on more modern versions of clang everything seems to be working as you also pointed out yourself.

**Comment by niosus** [comment] 2018-10-14 17:56
I will close this issue, as I cannot reproduce this and there seem to be nobody else experiencing this. Feel free to reopen it with more steps to reproduce this. Otherwise there is nothing I can be helpful here with. :disappointed:

**Closed by niosus** 2018-10-14 17:56 UTC
Labels: Linux, bug, cannot-reproduce
