### ISSUE TITLE
libclang completion doesn't work with clang version > 3.6

### ISSUE THREAD

**Issue by riazanovskiy** [niosus/EasyClangComplete#20] opened 2016-05-29 04:32 UTC
The completion works fine on the default setup. But the log says 
`INFO:EasyClangComplete.EasyClangComplete: falling back to using clang in a subprocess.`
I found out that on my system I have libclang.so, not libclang-3.8.so.1 
After I changed it completion stopped working
```
INFO:EasyClangComplete.EasyClangComplete: init completer based on libclang
INFO:EasyClangComplete.plugin.completion.base_complete: Getting version from command: `clang++ --version`
INFO:EasyClangComplete.plugin.completion.base_complete: Found clang version: 3.8
WARNING:EasyClangComplete.plugin.completion.lib_complete: cannot get default cindex with error: No module named 'EasyClangComplete.clang.cindex'
WARNING:EasyClangComplete.plugin.completion.lib_complete: using bundled one: EasyClangComplete.clang.cindex38
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 4
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 18
DEBUG:EasyClangComplete.EasyClangComplete:init completer for view id: 18
DEBUG:EasyClangComplete.plugin.plugin_settings: populating include dirs with current variables:
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_name = 
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_folder = /home/daniel/.config/sublime-text-3/Packages/EasyClangComplete
DEBUG:EasyClangComplete.plugin.plugin_settings: file_parent_folder = /home
DEBUG:EasyClangComplete.plugin.plugin_settings: include_dirs = ['/usr/include', '/home/daniel/.config/sublime-text-3/Packages/EasyClangComplete/src', '/usr/include/c++/6.1.1', '/usr/include/c++/6.1.1/x86_64-unknown-linux-gnu', '/usr/include/c++/6.1.1/backward', '/usr/local/include', '/usr/lib/clang/3.8.0/include', '/home/daniel']
DEBUG:EasyClangComplete.plugin.completion.lib_complete: searching for .clang_complete in /home/daniel up to /home/daniel/.config/sublime-text-3/Packages/EasyClangComplete
DEBUG:EasyClangComplete.plugin.completion.lib_complete: clang flags are: ['-std=gnu++1z', '-I/usr/include', '-I/home/daniel/.config/sublime-text-3/Packages/EasyClangComplete/src', '-I/usr/include/c++/6.1.1', '-I/usr/include/c++/6.1.1/x86_64-unknown-linux-gnu', '-I/usr/include/c++/6.1.1/backward', '-I/usr/local/include', '-I/usr/lib/clang/3.8.0/include', '-I/home/daniel']
DEBUG:EasyClangComplete.plugin.completion.lib_complete: compilation started for view id: 18
DEBUG:EasyClangComplete.plugin.completion.lib_complete: compilation done in 0.4559640884399414 seconds
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 18
DEBUG:root: adding error {'row': '20', 'file': '/home/daniel/test.cpp', 'col': '5', 'error': "unexpected namespace name 'std': expected expression"}
DEBUG:EasyClangComplete.plugin.error_vis: 1 error regions ready
DEBUG:EasyClangComplete.plugin.error_vis: showing error regions: [(325, 328)]
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 18
DEBUG:EasyClangComplete.plugin.error_vis: erasing error regions for view 18
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 18
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 329
DEBUG:EasyClangComplete.plugin.completion.lib_complete: started code complete for view 18
DEBUG:EasyClangComplete.plugin.completion.lib_complete: no completions
```

Error highlighting on save mostly doesn't work.
It seems that cindex38.codeComplete returns None at line 2606 because ptr is False for some reason.
I have Sublime Text 3114, Arch linux and clang 3.8

**Comment by niosus** [comment] 2016-05-29 09:28
Hm, ok. This sounds very logical. I believe, I will have to rework the way I manage cindex. It is a pain to work with libclang python bindings :)

On ubuntu, if you install `clang 3.8` you don't get `libclang.so`, you get `libclang-3.8.so.1`. This is one issue. I guess, I will reopen it separately.

The other one is the issue with `std` namespace not being recognized. I encountered the same error on my machine yesterday, and for now I don't know what causes it. It was not there before, so I will probably try different releases to try to find where I have introduced this bug. 

Sorry for the inconvenience. I will keep you posted as soon as I find out anything.

**Comment by niosus** [comment] 2016-05-29 09:47
Also, why do you use `-std=gnu++1z`? Any particular reason for this? Why not `-std=c++1z`? Can you try it?

**Comment by niosus** [comment] 2016-05-29 09:58
I have moved discussions about searching for a correct `.so` file to another issue #22

**Comment by riazanovskiy** [comment] 2016-05-29 22:46
It is same with all other flags (c++11, c++14, c++1z).

I don't think that the issue is related to namespace `std`. In libclang mode I have no completions at all, even for classes declared in the same file or any other namespace (e. g. `boost`).

**Comment by niosus** [comment] 2016-05-29 23:14
Could you also provide the file you are testing it on?

**Comment by riazanovskiy** [comment] 2016-05-29 23:19
You can use literally any file, for example test.cpp and test_vector.cpp from tests/

**Comment by niosus** [comment] 2016-05-29 23:23
Unfortunately I am clueless for now. I've just learned from issue #23 that libclang 3.8 can misbehave. Could you try the plugin with another version of clang? Like 3.6? If it is a hassle for you, I will try to install clang 3.8 on my system and see what happens.

**Comment by riazanovskiy** [comment] 2016-05-29 23:55
Same for clang 3.7.1

**Comment by niosus** [comment] 2016-05-30 16:27
May I still ask you to try clang 3.6? This is the one I have tested it on. Then we can have some common ground. For now I cannot reproduce the behavior.

**Comment by riazanovskiy** [comment] 2016-05-31 00:01
Wow! It works on clang 3.6.2 in libclang mode (after appropriate fix in cindex36.py).

**Comment by riazanovskiy** [comment] 2016-05-31 00:55
Am I right that you are using some python3 port of official libclang python bindings, with different release of cindex.py for each version of clang? 
Something works with clang 3.8 if I replace cindex38.py with the one from this repo https://bitbucket.org/Anteru/python3-libclang

**Comment by niosus** [comment] 2016-05-31 07:06
Yep, I am using a port of bindings, and they are far from guaranteed to be right. Thank you for a suggestion. 

May I ask which change did you do in `cindex36`?

**Comment by riazanovskiy** [comment] 2016-05-31 13:43
I had to change libclang.so file name to make it work on my system. This is about #22, not about this issue.

**Comment by niosus** [comment] 2016-05-31 13:54
Ok, I understand. then it seems that the fix would be to use libclang that you linked for clang version 3.8 (and I will adapt the official ones for 3.7). And then solving issue #22 Then this issue will be closed.

**Comment by riazanovskiy** [comment] 2016-05-31 14:31
Unfortunately that one doesn't work out of box. I didn't check it thoroughly, but sometimes it throws errors instead of completions.

**Comment by niosus** [comment] 2016-05-31 14:59
Ok, thanks for all that info. Then I will probably try to adapt the official ones to run with Python 3

**Comment by niosus** [comment] 2016-05-31 21:57
I had a look at the current `cindex38.py` and it is exactly the same as the official one after running `2to3` on it and enforcing `utf8` encoding. So I don't have any further idea what could be happening. I have installed clang 3.8 on my system and I do not get autocompletions just as in your case. In addition to that if I try it multiple times `plugin_host` eventually crashes.

I have tried to annotate what is being called from cindex 3.8 with no luck. Also I tried to blatantly replace `cindex3.8.py` with the contents of `cindex3.6.py` and it did not change the behavior by even a slightest bit. But the `plugin_host` does not crash :)

So, now I am totally clueless. I will continue searching what can cause this, maybe somebody has encountered this. For now, I suggest using clang 3.6

**Comment by niosus** [comment] 2016-05-31 22:08
Although, after using the cindex that you have linked: https://bitbucket.org/Anteru/python3-libclang the completions seem to work. I will keep that version for now. Will push it in the upcoming days.

**Comment by niosus** [comment] 2016-05-31 22:24
Also, seems like the relevant fix is inspired by http://reviews.llvm.org/D17226 as referenced [here](https://github.com/niosus/EasyClangComplete/blob/master/clang/cindex38.py#L2406) in the new `cindex38.py`

**Comment by niosus** [comment] 2016-06-03 15:43
@riazanovskiy I have replaced `cindex38.py` by another version and it is working for me with clang 3.8. Can you try it out? I will close the issue for now, but feel free to reopen if something is not working.

**Closed by niosus** 2016-06-03 15:43 UTC
Labels: bug, help wanted, Linux
