### ISSUE TITLE
Autocompletion is not working

### ISSUE THREAD

**Issue by Skonike** [niosus/EasyClangComplete#16] opened 2016-05-25 17:23 UTC
The autocompletion is not working. But, the highlight works.

My configuration : 
- Sublime Text Build 3114 (Default conf with plugin "Package Control" and "EasyClangComplete") 
- Ubuntu 15.10
- Ubuntu clang version 3.6.2-1
- libclang-3.6-dev 

Log :
> reloading plugin EasyClangComplete.EasyClangComplete
plugins loaded
> INFO:EasyClangComplete.EasyClangComplete: init completer based on libclang
INFO:EasyClangComplete.plugin.completion.base_complete: Getting version from command: `clang++ --version`
> INFO:EasyClangComplete.plugin.completion.base_complete: Found clang version: 3.6
WARNING:EasyClangComplete.plugin.completion.lib_complete: cannot get default cindex with error: No module named 'clang'
> WARNING:EasyClangComplete.plugin.completion.lib_complete: using bundled one: EasyClangComplete.clang.cindex36

**Comment by niosus** [comment] 2016-05-25 19:06
Well, this is very strange. The error highlight cannot work if auto completion doesn't. Especially with libclang. Do you have a single window of sublime text open or many? The log that you copied is totally ok. It just tells you that there are no python bindings installed in your system, so it uses the ones bundled with the plugin. 

Sometimes the completion may fail due to errors in source code. Are you sure this is not the case? Does auto completion work for a very simple dunmy case ?

**Comment by Skonike** [comment] 2016-05-25 19:57
I have a single window of sublime text open in a sigle file main.cpp.
main.cpp contains a very simple program : 
```
#include <vector>

int main(int argc, char const *argv[])
{
	std::vector<int> vTest;
	vTest.  // <-- no completion
	return 0;
}
```
I have erase the floder ~/.config/sublime-text-3 for be sure there is no conflict with other plugin or config.

**Comment by niosus** [comment] 2016-05-25 20:56
You said that the error highlights work. Do they highlight anything also in the example file?

**Comment by Skonike** [comment] 2016-05-25 22:09
Yes, if I write "vTest.error" and I save, then the text "error" is highlight in yellow and the following message is tagged : 
> no member named 'error' in 'std::vector

**Comment by niosus** [comment] 2016-05-25 22:35
Oh, this is strange. Have you configured the triggers for autocompletion for Sublime Text own settings as described in readme?

**Comment by Ekinoks** [comment] 2016-05-25 22:49
I have this in file ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings : 

> {
> 	"ignored_packages":
> 	[
> 		"Vintage"
> 	],
> 	"auto_complete_triggers":
>     [
>         {
>             "characters": ".:>",
>             "selector": "source.c++ - string - comment - constant.numeric"
>         }
>     ],
> }

**Comment by niosus** [comment] 2016-05-25 23:03
Strange... Can you try to switch the `use_libclang` setting to off just to check of binary-based completion works?

**Comment by Ekinoks** [comment] 2016-05-26 00:45
if I switch **use_libclang** to **false**, then auto-completion work but highlight don't work.

**Comment by niosus** [comment] 2016-05-26 09:02
Uh, for now I have no idea what causes this. I have the same clang version and both error highlight and autocompletion work for me for both libclang and clang binary mode. Moreover, the unit tests test just that. Autocompletion for vector passes unit tests on Ubuntu instance.

So I guess we need to find out what is different in your setup to fix this issue.

**Comment by niosus** [comment] 2016-05-27 18:50
Does anybody else on Ubuntu experience the same issue? It would really help me if I knew more about it.

**Comment by niosus** [comment] 2016-05-27 20:21
Also, @Skonike @Ekinoks do you see any completions printed to the console or are they empty?

**Comment by Ekinoks** [comment] 2016-05-27 23:16
I have all reinstalled, and I have the same probleme, but I have a new line error in console : 
> ERROR:EasyClangComplete.plugin.completion.lib_complete: no translation unit for view id %s

**Comment by niosus** [comment] 2016-05-29 09:43
Can you look if your issue is related to #20 ? Also, can you copy the full log while performing the following actions:

1. open sublime text
2. open example cpp file
3. save the file (you don't need to change anything there)
4. try to autocomplete something

I will really help me to identify the issue

**Comment by niosus** [comment] 2016-05-30 23:27
Have you tried it after the update? Can you please provide the output of what I have specified in my last comment? Thanks!

**Comment by Ekinoks** [comment] 2016-05-31 16:01
The problem is solved with the last update :)

**Comment by niosus** [comment] 2016-05-31 16:10
Awesome! I am glad to hear it! I will close this issue, but feel free to reopen it if the error repeats.

**Closed by niosus** 2016-05-31 16:10 UTC
Labels: bug, help wanted, Linux
