### ISSUE TITLE
Autocomplete starts one character after trigger

### ISSUE THREAD

**Issue by payoto** [niosus/EasyClangComplete#529] opened 2018-11-06 17:58 UTC
# System #

- Windows 7 64bits
- Sublime Text 3: build 3176
- Clang: output of `clang --version`

  - clang version 6.0.0 (tags/RELEASE_600/final)
  - Target: x86_64-pc-windows-msvc
  - Thread model: posix

I have a windows 10 machine at home and will look if the bug exists as well.

# Issue #

ECC does not start autocomplete after the triggers (using the defaults
`[ ".", "->", "::", " ", "	", "(", "[" ]`), it only provides the autocompletion after one
additional character.  I don't think that is the intended behaviour?

The autocompletion works otherwise.

# Minimal example #

	#include <vector>

	int main(int argc, char const *argv[])
	{
		std::vector<int> v;
		v.size();
		v.size(); // The line I added during this session
		return(0);
	}

Correct Autocompletion when starting a line.
![autocomplete_1](https://user-images.githubusercontent.com/18074599/48083278-b0d3c480-e1ec-11e8-90ff-1760b9f49274.png)

The trigger does not trigger autocompletion
![autocomplete_fail](https://user-images.githubusercontent.com/18074599/48083280-b3361e80-e1ec-11e8-8cff-6462f2856a7a.png)

After on character
![autocomplete_2](https://user-images.githubusercontent.com/18074599/48083287-b4ffe200-e1ec-11e8-9ee5-9657dcb45f90.png)

# The log #

[nocomplete_on_dot_.log](https://github.com/niosus/EasyClangComplete/files/2554328/nocomplete_on_dot_.log)

**Comment by niosus** [comment] 2018-11-07 11:08
No, that is definitely not the intended behavior. I will try to have a look this week into this.

**Comment by niosus** [comment] 2018-11-24 12:03
I cannot reproduce this issue on my linux and windows 10 machines... This probably means that there is something wrong with the basic triggers. The mechanism is that Sublime Text triggers the completion on the settings defined in [Preferences](https://github.com/niosus/EasyClangComplete/blob/master/Preferences.sublime-settings) file. If somebody has overridden them, then nothing will work. It seems that some other package has removed `"."` as a valid completion trigger in your installation of sublime text. Can you try to reproduce this on a clean setup?

**Comment by payoto** [comment] 2018-11-27 11:22
I get the same issue with a different completely new install of sublime text with the only package being ECC. I'll see if I can reproduce on my windows 10 machine.

I don't know if it would make a difference but I've only tried on the portable versions of sublime text 3. I'm also using a custom syntax (although I'm fairly certain I turned that off when I sent the example).

I'm attaching my user settings in case there is anything there (with some username credentials removed from the includes by`<...>`)
[USER-EasyClangComplete.sublime-settings.txt](https://github.com/niosus/EasyClangComplete/files/2619638/USER-EasyClangComplete.sublime-settings.txt)

I'll try to play around with settings and see if it gives me more information when I have a bit more time. Any suggestions on what to look out for (say in the log)?

Thanks for the help!

**Comment by niosus** [comment] 2018-11-27 21:56
Thanks for the info @payoto 
Your settings look ok to me. Maybe try to remove the target compiler setting? I have seen it causing weird bugs at times. But it still does not explain the issue that is reported here...

**Comment by payoto** [comment] 2018-11-27 23:20
I don't have the issue on my windows 10 system, either with a root install or a portable install of Sublime Text. Starts being a pretty niche bug.

**Comment by niosus** [comment] 2018-11-28 11:12
I'm not sure I will have the time to dive into it then. There are multiple reasons. I am not an expert at how Windows functions and in which way it can cause this issue. In addition to that that is a pretty old installation of Windows. I guess I will close this issue, but feel free to reopen if you encounter it on a modern system.

**Closed by niosus** 2018-11-28 11:12 UTC
Labels: bug, cannot-reproduce

**Comment by shuhaowu** [comment] 2019-07-12 02:55
I see the same issue on Linux. If it is related, I'm using NeoVintageous.

```
[ECC:DEBUG]:[tools.py]:[get_pos_status]:[MainThread]: matched trigger ' '.
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: this position has identifier: '(25, 2950)'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: returning existing completions
[ECC:DEBUG]:[tools.py]:[format_completions]:[MainThread]: adding clang completions to default ones
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-11]: on_modified_async view id 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-11]: on_modified_async view id 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-11]: on_modified_async view id 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-11]: on_modified_async view id 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[__remove_old_configs]:[Thread-29]: Skip young config: Age 2.4740562438964844 < 1800. View: 25.
#####
This is where the log is before I typed the character after the . that triggered the completion.
#####
[ECC:DEBUG]:[EasyClangComplete.py]:[on_modified_async]:[Dummy-11]: on_modified_async view id 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: on_query_completions view id 25
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: prefix: v, locations: [2956]
[ECC:DEBUG]:[tools.py]:[get_pos_status]:[MainThread]: matched trigger '.'.
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: this position has identifier: '(25, 2955)'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: starting async auto_complete with id: (25, 2955)
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: showing default completions
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-8]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-8]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7f5316edc8d0>
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: started code complete for view 25
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: using older version of clang: 3.8.0
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: code complete done in 0.0053708553314208984 seconds
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: Current trigger: '1.'
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: Current sanitized_trigger: '.'
[ECC:DEBUG]:[lib_complete.py]:[complete]:[Thread-8]: completions: [['vy\tfloat vy', 'vy'], ['x\tfloat x', 'x'], ['w\tfloat w', 'w'], ['y\tfloat y', 'y'], ['h\tfloat h', 'h'], ['vx\tfloat vx', 'vx']]
[ECC:DEBUG]:[tools.py]:[show_auto_complete]:[Thread-8]: reload completion tooltip
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: on_query_completions view id 25
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: prefix: v, locations: [2956]
[ECC:DEBUG]:[tools.py]:[get_pos_status]:[MainThread]: matched trigger '.'.
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: this position has identifier: '(25, 2955)'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_query_completions]:[MainThread]: returning existing completions
[ECC:DEBUG]:[tools.py]:[format_completions]:[MainThread]: adding clang completions to default ones
```

**Comment by shuhaowu** [comment] 2019-07-13 13:58
I figured out a workaround. I added the content of Preferences.sublime-settings within this repo to my personal sublime settings and it works.

`on_query_completions` is not getting called when `.` is pressed unless this is done.

Why is Preferences.sublime-settings not automatically merged with the sublime setting when the plugin is loaded?
