### ISSUE TITLE
Undeclared identifier error on Windows

### ISSUE THREAD

**Issue by spin0za** [niosus/EasyClangComplete#306] opened 2017-08-19 15:35 UTC
Hi, I've attached all the info needed I could think of. I'm sure that the include path is correct and headers are in there. I'm really confused what happened. Tried using a .clang_complete file, reset, restart, etc. None worked.

[log.txt](https://github.com/niosus/EasyClangComplete/files/1236462/log.txt)
[test.cpp.txt](https://github.com/niosus/EasyClangComplete/files/1236463/test.cpp.txt)

- Sublime Text version: 3126
- which system are you on: Windows 10

My ECC user settings:

```
{
    "show_type_info": false,
    "common_flags":
    [
        "-IC:/MinGW/mingw32/lib/gcc/mingw32/4.8.1/include/c++",
    ],
}
```

![error](https://user-images.githubusercontent.com/5843313/29488046-20e5fdc6-84d1-11e7-8165-edf4a993e8ad.png)

**Comment by niosus** [comment] 2017-08-20 17:37
Hey, @spin0za sorry that it doesn't really work for you. I am afraid, I am far from being an expert on Windows and using MinGW. The log, however, seems to suggest that everything works as expected and the issue is somewhere in the configuration. The issue is that libclang cannot find STL on Windows on its own. I don't really use Windows, so I can't tell you exactly what to do.

I guess the things that we can do are the following:
- you can check out this comment https://github.com/niosus/EasyClangComplete/issues/175#issuecomment-266980247 and try to adapt those settings to your case. Please make sure to post your solution in case it works for you.
- you can try to educate me on how to quickly set up a working environment with MinGW on Windows, so that I could have a setup to reproduce this bug. I wanted to get to this for a long time already, but I just seem to never really find the time.

**Comment by niosus** [comment] 2017-08-22 05:55
I am glad it solved the issue for you at least partially. I hope I will have the time to install everything on Windows and make sure it works at some point.

As for the Visual Studio. As far as I remember, libclang is able to find includes for Visual C++ on its own as of version 4.0, so probably that was why something was working. This is also something that I test against in the unit tests on Appveyor.

**Comment by niosus** [comment] 2017-08-22 05:55
I will close this issue as a duplicate of #175

**Closed by niosus** 2017-08-22 05:55 UTC
Labels: bug, MinWG / Cygwin, Windows
