### ISSUE TITLE
"EasyClangComplete: "use_libclang" is false" but it is not!

### ISSUE THREAD

**Issue by raimon-fa** [niosus/EasyClangComplete#336] opened 2017-10-12 15:18 UTC
- ST 3  
- Ubuntu 14.04.
After installing EasyClangComplete with package control, apart from not working, a message keeps popping out saying 

                EasyClangComplete:
                "use_libclang" is false
                "show_type_info" is true.

                Unfortunately, there is no way to show type info
                if you are not using libclang.

                Please use libclang or set "show_type_info" to false.

I checked but "use_libclang" but it is not false, not in the default settings nor in the user ones.
What do you think the problem is?

I attach the text output in the console when the window pops up.
[console_output.txt](https://github.com/niosus/EasyClangComplete/files/1382381/console_output.txt)

Thanks a lot.

**Comment by niosus** [comment] 2017-10-13 01:27
This happens when there was a problem detecting your libclang. In this case the plugin falls back to not using it. It is confusing, I agree. 

Please update the description of the issue following the issue template. I created it for a reason. Without the log there is nothing I can help you with.

**Comment by raimon-fa** [comment] 2017-10-13 11:13
Sorry, I didn't read the template careful enough. I attached now the file with the console output. Thanks for your help!

**Comment by niosus** [comment] 2017-10-16 06:57
Thanks for updating the issue. However, it is still not really enough. Please follow the instructions carefully. I will need a full log from the moment of starting sublime text to the moment you get an error. Your current log starts with the error which does not give me any new information about the cause of the issue.

**Comment by raimon-fa** [comment] 2017-10-17 13:17
Sorry again. I attach here the full log, I hope it will suffice. Thanks again for your help and sorry for the inconveniences.
[console_output.txt](https://github.com/niosus/EasyClangComplete/files/1391091/console_output.txt)

**Comment by niosus** [comment] 2017-10-18 04:27
Ok, so the reason for the error you are seeing is deeper than what you initially asked. Here is the error trace:
```
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-5]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[tools.py]:[run_command]:[Dummy-5]: clang process finished with code: 127
[ECC:DEBUG]:[tools.py]:[run_command]:[Dummy-5]: clang process output: 
/bin/sh: 1: clang++: not found

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 201, in on_activated_async
    settings = self.settings_manager.settings_for_view(view)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 51, in settings_for_view
    self.__init_for_view(view)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 99, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 113, in update_from_view
    self.__update_wildcard_values(view)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 285, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 725, in get_clang_version_str
    return cls._get_regular_clang_version_str(output_text)
  File "/home/postdoc1/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 736, in _get_regular_clang_version_str
    raise RuntimeError(" Couldn't find clang version in clang version "
RuntimeError:  Couldn't find clang version in clang version output.
```

The issue happens because `clang++` is not found in your path. Make sure you have installed clang and not, say `clang-3.8`. If you did the latter, make sure to set the `clang_binary` setting to a version that you can call from a terminal. I will close this issue as this is a configuration issue. Feel free to continue discussing your next steps here.

**Closed by niosus** 2017-10-18 04:27 UTC
Labels: awaiting-feedback

**Comment by raimon-fa** [comment] 2017-10-18 07:22
Thanks! I just needed to replace clang++ to clang++-3.9 preferences.
