### ISSUE TITLE
Backslashes in Windows paths confuse Python re

### ISSUE THREAD

**Issue by alpo** [niosus/EasyClangComplete#108] opened 2016-10-27 17:41 UTC
# Environment

Sublime Text 3126
Clang 3.9.0
tried both EasyClangComplete from package control and master branch from Github
settings:
{
	"use_libclang" : false,
	"verbose" : true,
}

# Log at launch:

INFO:EasyClangComplete.EasyClangComplete: init completer based on clang from cmd
INFO:EasyClangComplete.plugin.completion.base_complete: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.completion.base_complete: Found clang version: 3.9
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 31
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.base_complete: flags handler not initialized. Do it.
DEBUG:EasyClangComplete.EasyClangComplete:init completer for view id: 31
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.flags_manager: expanded CMAKE_PREFIX_PATHs: ['C:\\Users\\John/relative/path', '/absolute/path']
DEBUG:EasyClangComplete.plugin.plugin_settings: populating include dirs with current variables:
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_name = db-replicator
DEBUG:EasyClangComplete.plugin.plugin_settings: project_base_folder = C:\Users\John\Documents\git\db-replicator
DEBUG:EasyClangComplete.plugin.plugin_settings: file_parent_folder = C:\Users\John\Documents\git\db-replicator
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 114, in on_activated_async
    self.completer.init(view, self.settings)
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\bin_complete.py", line 166, in init
    includes = settings.populate_include_dirs(view)
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\plugin_settings.py", line 285, in populate_include_dirs
    "(\$project_base_path)", self.project_base_folder, include_dir)
  File "./python3.3/re.py", line 170, in sub
  File "./python3.3/re.py", line 309, in _subx
  File "./python3.3/re.py", line 296, in _compile_repl
  File "./python3.3/sre_parse.py", line 801, in parse_template
sre_constants.error: missing group name

# Log after C++ file opening:

DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 32
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `Plain text`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 31
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 111, in on_activated_async
    if not self.completer.needs_init(view):
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\base_complete.py", line 105, in needs_init
    if self.exists_for_view(view.buffer_id()):
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\bin_complete.py", line 122, in exists_for_view
    if len(self.flags_dict[view_id]) > 0:
TypeError: object of type 'NoneType' has no len()

# Log after typing "." in C++ source

DEBUG:EasyClangComplete.plugin.tools: matched trigger '.'.
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 2039
DEBUG:EasyClangComplete.EasyClangComplete: showing default completions
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_modified_async view id 31
Exception in thread Thread-22:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\bin_complete.py", line 197, in complete
    output_text = self.run_clang_command(view, "complete", cursor_pos)
  File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\bin_complete.py", line 279, in run_clang_command
    flags=" ".join(flags))
TypeError: can only join an iterable

**Comment by niosus** [comment] 2016-10-27 19:05
Thank you for a nice bug report. This is really weird, as this doesn't happen on my system. The key seems to be `missing group name` in the first log you have submitted. I will try to reproduce this on the weekend.

**Comment by niosus** [comment] 2016-10-28 21:47
I had to revert the changes partially as they break the execution. For example if there is a dot or slash as part of the path - they get escaped. This is slightly unwanted. 

I still don't fully understand what exactly is the problem on your side and I am slightly confused as all Windows tests pass properly. Feel free to submit some other solution to fix the problem on your side. 

Otherwise, please provide some more details on what exactly is failing.

**Comment by alpo** [comment] 2016-10-29 08:40
I'm trying to reproduce in python 3.5 command line, but getting different error

>>> import re
>>> project_base_folder = "C:\\Users\\John\\Documents\\git\\db-replicator"
>>> print(project_base_folder)
C:\Users\John\Documents\git\db-replicator
>>> re.sub("(\$project_base_path)", project_base_folder, "/usr/include")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.5/re.py", line 325, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.5/re.py", line 312, in _compile_repl
    p = sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.5/sre_parse.py", line 872, in parse_template
    raise s.error("missing <")
sre_constants.error: missing < at position 25

Another experiments

>>> project_base_folder = "C:\\Users\\John\\Documents\\git"
>>> re.sub(r"\$project_base_path", project_base_folder, "/usr/include")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.5/re.py", line 325, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.5/re.py", line 312, in _compile_repl
    p = sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.5/sre_parse.py", line 872, in parse_template
    raise s.error("missing <")
sre_constants.error: missing < at position 25

Another 

>>> project_base_folder = "C:\\Users\\John\\Documents"
>>> re.sub(r"\$project_base_path", project_base_folder, "/usr/include")
'/usr/include'

So it is reaction on unescaped '\g' in the path (inserting of group) and 2nd string in the re.sub should be escaped.

**Comment by niosus** [comment] 2016-10-29 16:41
You have already sibmitted a pull request before, could you please do it again using the way @rchl suggested? Just replacing `\` by `\\`. I believe this has to solve your issue. If you don't want to write another pull request, I could do it, but I think it's better this way, as you'll know instantly if this fixes your issue.

**Comment by niosus** [comment] 2016-10-30 11:30
I have merged your pull request, so I am closing the issue for now.

**Closed by niosus** 2016-10-30 11:30 UTC
Labels: bug, cannot reproduce
