### ISSUE TITLE
[Bug] ECC is not working when file is untitled.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [niosus/EasyClangComplete#233] opened 2017-03-23 11:46 UTC
As the title.

**Comment by niosus** [comment] 2017-03-23 11:52
That is probably because this file has no syntax in sublime text yet.

**Comment by ooJerryLeeoo** [comment] 2017-03-23 11:52
I've set the untitled file syntax to `C++`

**Comment by niosus** [comment] 2017-03-23 11:53
Then I will need the output from the console with `"verbose": true` setting. Otherwise, not much I can tell.

**Comment by ooJerryLeeoo** [comment] 2017-03-23 11:57
![2017-03-23 19_56_41](https://cloud.githubusercontent.com/assets/20783502/24246545/dbaba56e-1002-11e7-838f-7ddc3bc1d703.gif)

**Comment by ooJerryLeeoo** [comment] 2017-03-23 11:59
In the case when I type `printf`, `scanf`, `return`, the auto_complete menu not show up.

**Comment by ooJerryLeeoo** [comment] 2017-03-23 12:02
Here's file titled version of the gif:

![2017-03-23 20_00_59](https://cloud.githubusercontent.com/assets/20783502/24246676/869a7d9c-1003-11e7-9447-16f0feba4c2c.gif)

**Comment by niosus** [comment] 2017-03-23 12:52
Ok, I can reproduce this. Will look into it at some point. Why not just saving file before writing code there?

Also, I will remove the gifs. They are quite distracting to me and the description is more than enough to understand what is going on.

**Comment by ooJerryLeeoo** [comment] 2017-03-23 13:26
I am saving file before writing code, but I just found this bug.

**Comment by niosus** [comment] 2017-03-23 14:08
I'm not really sure how much I want to fix it :) I know where it comes from, but I know why we check if the file exists. We had some nasty crashes in libclang when file was not saved before wise and honestly I don't really want to dive into this again. I believe it is ok to just save the file before one gets completions in it and will close it with `won't fix` for now. If this is a great deal to somebody, one can try to convince me otherwise or open a pull request on this.

**Closed by niosus** 2017-03-23 14:08 UTC
Labels: bug
